# Sprint 機械学習スクラッチ

## 【問題1】train_test_splitのスクラッチ

In [53]:
def scratch_train_test_split(X, y, train_size=0.8,):
    """
    検証用データを分割する。

    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
      学習データ
    y : 次の形のndarray, shape (n_samples, )
      正解値
    train_size : float (0<train_size<1)
      何割をtrainとするか指定

    Returns
    ----------
    X_train : 次の形のndarray, shape (n_samples, n_features)
      学習データ
    X_test : 次の形のndarray, shape (n_samples, n_features)
      検証データ
    y_train : 次の形のndarray, shape (n_samples, )
      学習データの正解値
    y_test : 次の形のndarray, shape (n_samples, )
      検証データの正解値
    """
    #ここにコードを書く
    n_samples = X.shape[0]
    n_test = np.round((1-train_size) * n_samples).astype(int)
    n_train= n_samples - n_test
    
    rng = np.random.RandomState(seed=None)
    permutation = rng.permutation(n_samples)
    ind_test = permutation[:n_test]
    ind_train = permutation[n_test:(n_test + n_train)]

    X_train = X[ind_train]
    X_test = X[ind_test]
    y_train = y[ind_train]
    y_test = y[ind_test]

        
    pass

    return X_train, X_test, y_train, y_test

    def _iter_indices(self, X, y=None, groups=None):
        n_samples = _num_samples(X)
        n_train, n_test = _validate_shuffle_split(
            n_samples, self.test_size, self.train_size,
            default_test_size=self._default_test_size)

        rng = check_random_state(self.random_state)
        for i in range(self.n_splits):
            # random partition
            permutation = rng.permutation(n_samples)
            ind_test = permutation[:n_test]
            ind_train = permutation[n_test:(n_test + n_train)]
            yield ind_train, ind_test

### train_test_splitのソースの中
    if shuffle is False:
        if stratify is not None:
            raise ValueError(
                "Stratified train/test split is not implemented for "
                "shuffle=False")

        train = np.arange(n_train)
        test = np.arange(n_train, n_train + n_test)

    else:
        if stratify is not None:
            CVClass = StratifiedShuffleSplit
        else:
            CVClass = ShuffleSplit

        cv = CVClass(test_size=n_test,
                     train_size=n_train,
                     random_state=random_state)

        train, test = next(cv.split(X=arrays[0], y=stratify))

    return list(chain.from_iterable((safe_indexing(a, train),
                                     safe_indexing(a, test)) for a in arrays))

#### ShuffleSplitの中
　def __init__(self, n_splits=10, test_size=None, train_size=None,
                 random_state=None):
        super().__init__(
            n_splits=n_splits,
            test_size=test_size,
            train_size=train_size,
            random_state=random_state)
        self._default_test_size = 0.1

    def _iter_indices(self, X, y=None, groups=None):
        n_samples = _num_samples(X)
        n_train, n_test = _validate_shuffle_split(
            n_samples, self.test_size, self.train_size,
            default_test_size=self._default_test_size)

        rng = check_random_state(self.random_state)
        for i in range(self.n_splits):
            # random partition
            permutation = rng.permutation(n_samples)
            ind_test = permutation[:n_test]
            ind_train = permutation[n_test:(n_test + n_train)]
            yield ind_train, ind_test

In [ ]:
#試してみる

In [2]:
import numpy as np
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,)

In [54]:
X_train_1, X_test_1, y_train_1, y_test_1 = scratch_train_test_split(X, y, train_size=0.8,)

In [57]:
print(y_train)

[0 1 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0]


In [55]:
print(y_train_1)

[0 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 0]


In [28]:
X.shape[0]

40

In [40]:
train_size = 0.8
n_samples = X.shape[0]
n_test = np.floor((1-train_size) * n_samples).astype(int)
n_train= n_samples - n_test

In [32]:
print(n_samples)

40


In [41]:
rng = np.random.RandomState(seed=None)
permutation = rng.permutation(n_samples)
ind_test = permutation[:n_test]
ind_train = permutation[n_test:(n_test + n_train)]

In [44]:
print(rng)

In [49]:
#np.random.permutationでも書き換えられそう
a=np.random.permutation(n_samples)
b=rng.permutation(n_samples)

備忘とメモ：  
RandomState  
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.html

random.permutation  
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.permutation.html  

参考:https://qiita.com/kztsh/items/5afae48b2c2fd7dc20a5  

In [52]:
print(a)
print(b)

[24 15 25 33 28 23  0 20 39 30 27 37  4 13 10  1  5  9 36 32  6 38 12  7
 17 18  8 11 19 14 16 26 22 34 21 35  3 31 29  2]
[26 35  4 31 29 17 39 28 37 30  2 10 11  5 36 38 19 25 32 22 16 27  6 15
  7 18 14 24  9 21 23  1 33 12  8  0 13  3 20 34]


## 【問題2】 分類問題を解くコードの作成

In [169]:
##アイリスのデータセット
from sklearn.datasets import load_iris
a = load_iris()
import pandas as pd
X = pd.DataFrame(a.data,columns=["sepal_length","sepal_width","petal_length","petal_width"])
y = pd.DataFrame(a.target,columns=["Species"])
df = pd.concat([X,y],axis=1)
df_12 =df[df['Species'].isin([1,2])]
X =df_12.drop("Species", axis=1).values
y = df_12.Species.values

In [107]:
#print(X)
#print(df[df['Species']==1])
#print(df[df['Species'].isin([1,2])].head())
#display(df_12.Species.values)
#display(df.drop("Species", axis=1))
print(len(X))

150


In [133]:
##シンプルデータセット1作成コード
import numpy as np

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

In [128]:
##シンプルデータセット2作成コード
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [170]:
#訓練データとテストデータに分割
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y)

In [171]:
#ロジスティック回帰
from sklearn import linear_model
#インスタンス化　引数でloss="log" 他の引数はサンプル通り
lg = linear_model.SGDClassifier(loss="log",max_iter=1000, tol=1e-3)
#訓練
lg.fit(X_train, y_train)
#予測
y_pred = lg.predict(X_test)
# スコア
lg.score(X_test,y_test)

0.95

In [172]:
#SVM
from sklearn.svm import SVC
#インスタンス化
svc = SVC(gamma='auto')
#訓練
svc.fit(X_train, y_train)
#予測
y_pred = svc.predict(X_test)
# スコア
svc.score(X_test,y_test)

1.0

In [173]:
#決定木
from sklearn.tree import DecisionTreeClassifier
#インスタンス化
dt =DecisionTreeClassifier(random_state=0)
#訓練
dt.fit(X_train, y_train)
#予測
y_pred = dt.predict(X_test)
# スコア
dt.score(X_test,y_test)

0.95

## 【問題3】 回帰問題を解くコードの作成

In [180]:
#HOUSEのデータ取り込み
path ='/Users/toyodasatomi/Desktop/DIC/data/train.csv'
df = pd.read_csv(path)
X_k=df[['GrLivArea','YearBuilt']].values
y_k =df.SalePrice.values

In [181]:
#訓練データとテストデータに分割
X_train_k, X_test_k, y_train_k, y_test_k = scratch_train_test_split(X_k, y_k)

In [167]:
#display(df.SalePrice.head())
#display(df[['GrLivArea','YearBuilt']])

In [192]:
from sklearn import linear_model
#インスタンス化
sg = linear_model.SGDRegressor(max_iter=1000, tol=1e-3)
#学習
sg.fit(X_train_k, y_train_k)
#予測
y_pred_k = sg.predict(X_test_k)
# スコア
sg.score(X_test_k,y_test_k)

-1.705021127961164e+20

In [1]:
#print(y_pred_k)

In [187]:
print(y_k)

[208500 181500 223500 ... 266500 142125 147500]
