# Sprint 深層学習スクラッチ　畳み込みニューラルネットワーク1

### インポート

In [4]:
import numpy as np

### データ

In [ ]:
aaa

In [5]:
#小さな配列
x = np.array([1,2,3,4])
w = np.array([3, 5, 7])
b = np.array([1])
#誤差　Loss
delta_a = np.array([10, 20])

## 【問題1】チャンネル数を1に限定した1次元畳み込み層クラスの作成

In [98]:
#まとめるクラス
class Scratch1dCNNClassifier():

    #def __init__(self,):
        #self.W = w
        #self.B = b
        #self.lr = lr
        #self.B = b
        #self.W = w
        
    def fit(self,):
        #インスタンス化
        #optimizer = SGD(self.lr)
        self.FC1 = FC(w,b,N_in=4,Pading=0,Fil=3,Slide=1)
        
        #フォワードとバックフォワード
        A = self.FC1.forward(x)
        delta_b_1d,delta_w_1d,delta_x_list = self.FC1.backward(delta_a)
        
        #Z = self.FC3.backward(A)
        
        return A,delta_b_1d,delta_w_1d,delta_x_list

In [97]:
#フォワード
class FC:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self,w,b,N_in,Pading,Fil,Slide):
        #self.optimizer = optimizer
        # 指定の重みとバイアスを代入
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.W=w
        self.B =b
        self.N_in = N_in
        self.Pading = Pading
        self.Fil = Fil
        self.Slide = Slide
    
    def output_size(self,N_in,Pading,Fil,Slide):
        N_ount = (N_in+2*Pading-Fil/Slide)+1
        return N_ount


    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        self.X = X
        
        #アウトプットサイズ
        self.N_out = self.output_size(self.N_in,self.Pading,self.Fil,self.Slide)
        self.N_out_int = np.array(self.N_out).astype(np.int)


        
        a_1d=np.arange(self.N_out_int )
        
        for k in range(self.N_out_int):
            a = 0
            ab = 0
            for i in range(len(self.W)):
                a += self.X[k+i] * self.W[i] 
            ab = a+self.B
            np.put(a_1d,k,ab)      
        return a_1d
      
    def backward(self, delta_a):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
 
        #バイアスの更新
        delta_b_1d = delta_a[0]+delta_a[1]
        
        #重み（フィルタ）の結果格納のリスト
        delta_w_1d =np.arange(len(self.W))
        
        for k in range(len(self.W)):
            w_new = 0
            for i in range(self.N_out_int):
                w_new += delta_a[i] * self.X[i+k]
            np.put(delta_w_1d,k,w_new)
            
        #Xの更新
        #Xのアウトプットのリスト
        delta_x_list =  np.arange(len(self.X))
        
        for j in range(len(self.X)):
            delta_x = 0
            for s in range(len(self.W)):
                js=j-s
                if js < 0:
                    delta_x += 0*self.W[s]
                else:
                    if  js > self.N_out_int-1:
                        delta_x += 0*self.W[s]
                    else:
                        delta_x += delta_a[js]*self.W[s]
            np.put(delta_x_list,j,delta_x)
        
        # 更新
        #self = self.optimizer.update(self)
        
        return delta_b_1d,delta_w_1d,delta_x_list

In [62]:
# 更新式　いらない？
class SGD:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr):
        self.lr = lr
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """
        layer.W -= self.lr*layer.W_new
        layer.B -=  self.lr*layer.B_new

In [78]:
class SimpleInitializer:
    """
    変数代入によるシンプルな初期化
    Parameters
    ----------
    sigma : float
      ガウス分布の標準偏差
    """
    #def __init__(self):
        #self.sigma = sigma
    
    def W(self, w):
        """
        重みの初期化
        Parameters
        ----------
        n_nodes1 : int
          前の層のノード数
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        W :
        """
        W= w
        return W
    
    def B(self, b):
        """
        バイアスの初期化
        Parameters
        ----------
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        B :
        """
        B = b
        return B

## 【問題2】1次元畳み込み後の出力サイズの計算

In [124]:
def output_size_2(N,P,F,S):
    N_out = (N+2*P-F/S)+1
    return N_out

In [125]:
N_out = output_size_2(4,0,3,1)

In [11]:
print(N_out)

2.0


In [147]:
4+2*0-3/1+1

2.0

## 【問題3】小さな配列での1次元畳み込み層の実験

In [120]:
#小さな配列
x = np.array([1,2,3,4])
w = np.array([3, 5, 7])
b = np.array([1])
#誤差　Loss
delta_a = np.array([10, 20])

In [126]:
list_A=np.arange(N_out)

In [121]:
len(w)-1

2

In [127]:
#手計算でフォワード
a = 0
for k in range(N_out_int):
    a = 0
    ab = 0
    for i in range(len(w)):
        a += x[k+i] * w[i] 
    ab = a+b
    np.put(list_A,k,ab)

In [45]:
print(list_A)

[35. 50.]


In [39]:
print(x)

[1 2 3 4]


In [28]:
print(len(w)-1)

2


In [15]:
sli = 1
list_w =np.arange(len(w))

In [30]:
#print(np.round(test_out))
#print(N_out*1)
N_out_int = np.array(N_out).astype(np.int)

In [28]:
print(len(w))

3


In [31]:
print(N_out_int)

2


In [32]:
#手計算でバックフォワード [W]
B = delta_a[0]+delta_a[1]
#print(B)

for k in range(len(w)):
    w_new = 0
    for i in range(N_out_int):
        w_new += delta_a[i] * x[i+k]
    np.put(list_w,k,w_new)

#list_A[]

In [33]:
print(list_w)

[ 50  80 110]


In [69]:
#手計算でバックフォワード [X]
#X = delta_a[0]+delta_a[1]
#print(B)

list_x =  np.arange(len(x))

for j in range(len(x)):
    delta_x = 0
    for s in range(len(w)):
        js=j-s
        print('js',js)
        if js < 0:
            delta_x += 0*w[s]
            print('1',delta_x)
        else:
            if  js > N_out_int-1:
                delta_x += 0*w[s]
                print('2',delta_x)
            else:
                delta_x += delta_a[js]*w[s]
                print('3',delta_x)
    print('4',delta_x)
    np.put(list_x,j,delta_x)

#list_A[]

js 0
3 30
js -1
1 30
js -2
1 30
4 30
js 1
3 60
js 0
3 110
js -1
1 110
4 110
js 2
2 0
js 1
3 100
js 0
3 170
4 170
js 3
2 0
js 2
2 0
js 1
3 140
4 140


In [43]:
print(len(x))

4


In [45]:
print(len(w))

3


In [46]:
print(N_out_int)

2


In [70]:
print(list_x)

[ 30 110 170 140]


### クラス化したもので実行してみる。

In [99]:
S1C = Scratch1dCNNClassifier()

In [100]:
A_t,delta_b_1d_t,delta_w_1d_t,delta_x_list_t = S1C.fit()

In [101]:
print(A_t)

[35 50]


In [102]:
print(delta_b_1d_t)

30


In [103]:
print(delta_w_1d_t)

[ 50  80 110]


In [105]:
print(delta_x_list_t)

[ 30 110 170 140]


In [106]:
#イマイチなクラスの作りになったがとりあえずは想定するものは算出できた

In [21]:
#工夫
x_k = np.array([1, 2, 3, 4])
w_k = np.array([3, 5, 7])

a = np.empty((2, 3))

indexes0 = np.array([0, 1, 2]).astype(np.int)
indexes1 = np.array([1, 2, 3]).astype(np.int)

In [22]:
x = np.array([1, 2, 3, 4])
indexes = np.array([[0, 1, 2], [1, 2, 3]]).astype(np.int)

print(x[indexes])

[[1 2 3]
 [2 3 4]]


In [23]:
x = np.array([1,2,3,4])
w = np.array([3, 5, 7])
b = np.array([1])
idx1 = np.arange(w.shape[0])
idx2 = np.arange(w.shape[0] - 1).reshape(-1, 1)
index = idx1 + idx2
print('idx1',idx1)
print('idx2',idx2)
print('index',index)
a = np.dot(x[index], w.T) + b
a

idx1 [0 1 2]
idx2 [[0]
 [1]]
index [[0 1 2]
 [1 2 3]]


array([35, 50])

## 【問題4】チャンネル数を限定しない1次元畳み込み層クラスの作成

In [109]:
x_4 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]]) # shape(2, 4)で、（入力チャンネル数、特徴量数）である。
w_4 = np.ones((3, 2, 3))
b_4 = np.array([1, 2, 3]) #

In [108]:
print(w_4)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [148]:
print(b_4[0])

1


### フォワード手計算

In [113]:
#手計算してみる：　フォワード
print(x_4[0])

[1 2 3 4]


In [117]:
#チャネル数
print(x_4.shape[0])

2


In [118]:
#フィルタ数
print(w_4.shape[0])

3


In [143]:
#チャンネル1のフィルタ
print(w_4[0,0,0])
print(w_4[0,0,1])

1.0
1.0


In [116]:
#チャンネル2のフィルタ
print(w_4[0,1])

[1. 1. 1.]


In [140]:
test =np.arange(3)
test2 =np.arange(3)

In [150]:
print(b)

[1]


In [162]:
#一旦チャネル数１→2
#チャネルの数　 = 2
len_x_4 = x_4.shape[0]
#出力の数 (N,P,F,S):
N_out_c = output_size_2(4,0,3,1)
N_out_c_int = np.array(N_out_c).astype(np.int)

#返すリスト
a_c_list=np.zeros(N_out_int)
ab_c_list=np.zeros(N_out_int)
a = []

#繰り返す
for c in range(len_x_4):
    for k in range(N_out_c_int):
        a = 0
        ab = 0
        for i in range(len(w)):
            a += x_4[c,k+i] * w_4[0,c,i] 
            print('a',a)
            #ab = a+b_4[0]
        np.put(a_c_list,k,a)
        print('a_c_list1',a_c_list)
    #a.append(a_c_list1)
    print('a_c_list2',a_c_list)
    ab_c_list += a_c_list
print('a_c_list3',a_c_list)    
ab_c_list += b_4[0]
print('ab_c_list',ab_c_list)

a 1.0
a 3.0
a 6.0
a_c_list1 [6. 0.]
a 2.0
a 5.0
a 9.0
a_c_list1 [6. 9.]
a_c_list2 [6. 9.]
a 2.0
a 5.0
a 9.0
a_c_list1 [9. 9.]
a 3.0
a 7.0
a 12.0
a_c_list1 [ 9. 12.]
a_c_list2 [ 9. 12.]
a_c_list3 [ 9. 12.]
ab_c_list [16. 22.]


In [232]:
#一旦チャネル数１→2 とフィルタ数　３
#フィルタ数
len_w_4=w_4.shape[0]
#チャネルの数　 = 2
len_x_4 = x_4.shape[0]
#出力の数 (N,P,F,S):
N_out_c = output_size_2(4,0,3,1)
N_out_c_int = np.array(N_out_c).astype(np.int)

#返すリスト
a_c_list=np.zeros(N_out_int)
#サムして、バイアス足したもの
ab_c_list=np.zeros(N_out_int)
#フィルタ分貯めたもの
arr = np.empty((0,2), int)

a = []

#繰り返す
for f in range(len_w_4):
    for c in range(len_x_4):
        for k in range(N_out_c_int):
            a = 0
            ab = 0
            for i in range(len(w)):
                a += x_4[c,k+i] * w_4[f,c,i] 
                print('a',a)
                #ab = a+b_4[0]
            np.put(a_c_list,k,a)
            print('a_c_list1',a_c_list)
        #a.append(a_c_list1)
        print('a_c_list2',a_c_list)
        ab_c_list += a_c_list
    print('a_c_list3',a_c_list)    
    ab_c_list += b_4[f]
    print('ab_c_list4',ab_c_list)
    arr = np.append(arr,np.array([ab_c_list]), axis=0)
    print('arr',arr)
    ab_c_list = 0

a 1.0
a 3.0
a 6.0
a_c_list1 [6. 0.]
a 2.0
a 5.0
a 9.0
a_c_list1 [6. 9.]
a_c_list2 [6. 9.]
a 2.0
a 5.0
a 9.0
a_c_list1 [9. 9.]
a 3.0
a 7.0
a 12.0
a_c_list1 [ 9. 12.]
a_c_list2 [ 9. 12.]
a_c_list3 [ 9. 12.]
ab_c_list4 [16. 22.]
arr [[16. 22.]]
a 1.0
a 3.0
a 6.0
a_c_list1 [ 6. 12.]
a 2.0
a 5.0
a 9.0
a_c_list1 [6. 9.]
a_c_list2 [6. 9.]
a 2.0
a 5.0
a 9.0
a_c_list1 [9. 9.]
a 3.0
a 7.0
a 12.0
a_c_list1 [ 9. 12.]
a_c_list2 [ 9. 12.]
a_c_list3 [ 9. 12.]
ab_c_list4 [17. 23.]
arr [[16. 22.]
 [17. 23.]]
a 1.0
a 3.0
a 6.0
a_c_list1 [ 6. 12.]
a 2.0
a 5.0
a 9.0
a_c_list1 [6. 9.]
a_c_list2 [6. 9.]
a 2.0
a 5.0
a 9.0
a_c_list1 [9. 9.]
a 3.0
a 7.0
a 12.0
a_c_list1 [ 9. 12.]
a_c_list2 [ 9. 12.]
a_c_list3 [ 9. 12.]
ab_c_list4 [18. 24.]
arr [[16. 22.]
 [17. 23.]
 [18. 24.]]


In [172]:
b = []

In [177]:
c = np.append(b,a_c_list,axis=0)
print(c)
print(a_c_list)

[ 9. 12.]
[ 9. 12.]


In [175]:
np.append(c,a_c_list,axis=0)

array([ 9., 12.,  9., 12.])

In [184]:
np.hstack([c,a_c_list])

array([ 9., 12.,  9., 12.])

In [213]:
c =np.array([])
print(c)
print(a_c_list)

[]
[ 9. 12.]


In [205]:
c =np.append(c,np.array([[a_c_list]]))

In [221]:
print(a_c_list)

[ 9. 12.]


In [223]:
arr = np.empty((0,2), int)
print(arr)
arr = np.append(arr,np.array([a_c_list]), axis=0)
print(arr)
arr = np.append(arr,np.array([a_c_list]), axis=0)
print(arr)

[]
[[ 9. 12.]]
[[ 9. 12.]
 [ 9. 12.]]


In [233]:
arr.shape

(3, 2)

In [235]:
print(arr[0,0])

16.0


In [239]:
print(w_4[0,1])

[1. 1. 1.]


### バックフォワード[W]手計算

In [251]:
#仮のロス 設定
loss_test = np.array([[9,11],[32,35],[52,56]])
loss_w2 = np.array([32,35])
loss_w3 = np.array([52,56])

In [272]:
print(loss_test[0,1])
print(loss_test.shape)

11
(3, 2)


In [281]:
#フィルタ1つ
loss_test[0,0]

#ロスのシャープ
len_loss_test =  loss_test.shape
#フィルタの長さ　3
len_w_4=w_4.shape[0]
print(len_w_4)
#チャネルの数　 = 2
len_x_4 = x_4.shape

3


In [279]:
print(len_x_4[0])

2


In [296]:
#フィルタ1
#loss_out_arr= np.empty((0,len_w_4), int)
loss_out_arr= np.zeros([2,3])
loss_out_arr_cul= np.empty((0,len_w_4), int)

for k in range(len_loss_test[1]):
    loss_out_arr_cul= np.empty((0,len_w_4), int)
    for i in range(len_x_4[0]):
        loss_0 = loss_test[0,k]*x_4[i,k:k+len_w_4]
        print('loss_0',loss_0)
        loss_out_arr_cul=np.append(loss_out_arr_cul,np.array([loss_0]), axis=0)
        print('loss_out_arr',loss_out_arr)
    loss_out_arr +=loss_out_arr_cul
    print('loss_out_arr',loss_out_arr)

loss_0 [ 9 18 27]
loss_out_arr [[0. 0. 0.]
 [0. 0. 0.]]
loss_0 [18 27 36]
loss_out_arr [[0. 0. 0.]
 [0. 0. 0.]]
loss_out_arr [[ 9. 18. 27.]
 [18. 27. 36.]]
loss_0 [22 33 44]
loss_out_arr [[ 9. 18. 27.]
 [18. 27. 36.]]
loss_0 [33 44 55]
loss_out_arr [[ 9. 18. 27.]
 [18. 27. 36.]]
loss_out_arr [[31. 51. 71.]
 [51. 71. 91.]]


In [ ]:
arr = np.empty((0,2), int)

In [266]:
aaa = np.zeros([0,2])

In [291]:
print(loss_out_arr)

[[ 9 18 27]
 [18 27 36]
 [22 33 44]
 [33 44 55]]


In [ ]:
#フィルタ１→3
#loss_out_arr= np.empty((0,len_w_4), int)
loss_out_arr= np.zeros([2,3])
loss_out_arr_cul= np.empty((0,len_w_4), int)

for k in range(len_loss_test[1]):
    loss_out_arr_cul= np.empty((0,len_w_4), int)
    for i in range(len_x_4[0]):
        loss_0 = loss_test[0,k]*x_4[i,k:k+len_w_4]
        print('loss_0',loss_0)
        loss_out_arr_cul=np.append(loss_out_arr_cul,np.array([loss_0]), axis=0)
        print('loss_out_arr',loss_out_arr)
    loss_out_arr +=loss_out_arr_cul
    print('loss_out_arr',loss_out_arr)

In [406]:
dd = np.zeros((w_4.shape))
print(dd[0])

[[0. 0. 0.]
 [0. 0. 0.]]


In [300]:
w_4.shape

(3, 2, 3)

In [370]:
print(loss_out_arr.shape)

(2, 3)


In [350]:
np.putmask(dd[0],[0,1,2,3,4,5],loss_out_arr) 
print(dd)

[[[ 0. 51. 71.]
  [51. 71. 91.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [387]:
arr_w= np.empty((0,len_w_4), int)
arr_w = np.append(arr_w,np.array(loss_out_arr), axis=0)
#arr_w = np.append(arr_w,np.array([loss_out_arr[1]]), axis=0)

In [402]:
print(arr_w)

[[31. 51. 71.]
 [51. 71. 91.]
 [31. 51. 71.]
 [51. 71. 91.]
 [31. 51. 71.]
 [51. 71. 91.]]


In [401]:
arr_w = np.vstack((arr_w,loss_out_arr))

In [2]:
%history

%history
%history
