# Sprint 深層学習スクラッチ 畳み込みニューラルネットワーク2

### インポート

In [1]:
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
import numpy as np

### データセット 

In [5]:
from keras.datasets import mnist

Using TensorFlow backend.


In [6]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
print(X_train.shape)

(60000, 28, 28)


In [8]:
X_2d = np.reshape(X_train,[60000,1,28,28])

In [10]:
#print(X_2d[0])

In [9]:
#wとbを仮に設定
w_2d = np.ones((3, 3))
b_2d = np.array([1]) #

In [10]:
print(w_2d.shape)

(3, 3)


In [13]:
#w_2d_re = np.reshape(w_2d,[3,3,3])

In [15]:
#print(w_2d_re)

In [12]:
w_2d_re = np.ones((3, 3,3))

## 【問題1】2次元畳み込み層の作成

### 手計算でフォワード

In [21]:
# 手計算でフォワード
#a_1d=np.arange(N_h_out_int,N_h_out_int)
loss_out_arr_cul= []
for i in range(N_h_out_int):
    for  j in range(N_h_out_int):
        a = 0
        ab = 0
        for s in range(w_2d.shape[1]):
            #a = 0
            #ab = 0
            for t in range(w_2d.shape[0]):
                a += X_2d[0,0,i+s, j+t] * w_2d[s,t] 
                print('j,i,t,s',i+s,j+t,s,t)
            print('A')
        print('B')
        ab = a+b_2d
        loss_out_arr_cul.append(ab)
        #a_2d = np.reshape(loss_out_arr_cul,[26,26])
    print('C')
            #ab = a+self.B
             #print('ab',ab)
            #np.put(a_1d,k,ab)      
a_2d = np.reshape(loss_out_arr_cul,[26,26])

j,i,t,s 0 0 0 0
j,i,t,s 0 1 0 1
j,i,t,s 0 2 0 2
A
j,i,t,s 1 0 1 0
j,i,t,s 1 1 1 1
j,i,t,s 1 2 1 2
A
j,i,t,s 2 0 2 0
j,i,t,s 2 1 2 1
j,i,t,s 2 2 2 2
A
B
j,i,t,s 0 1 0 0
j,i,t,s 0 2 0 1
j,i,t,s 0 3 0 2
A
j,i,t,s 1 1 1 0
j,i,t,s 1 2 1 1
j,i,t,s 1 3 1 2
A
j,i,t,s 2 1 2 0
j,i,t,s 2 2 2 1
j,i,t,s 2 3 2 2
A
B
j,i,t,s 0 2 0 0
j,i,t,s 0 3 0 1
j,i,t,s 0 4 0 2
A
j,i,t,s 1 2 1 0
j,i,t,s 1 3 1 1
j,i,t,s 1 4 1 2
A
j,i,t,s 2 2 2 0
j,i,t,s 2 3 2 1
j,i,t,s 2 4 2 2
A
B
j,i,t,s 0 3 0 0
j,i,t,s 0 4 0 1
j,i,t,s 0 5 0 2
A
j,i,t,s 1 3 1 0
j,i,t,s 1 4 1 1
j,i,t,s 1 5 1 2
A
j,i,t,s 2 3 2 0
j,i,t,s 2 4 2 1
j,i,t,s 2 5 2 2
A
B
j,i,t,s 0 4 0 0
j,i,t,s 0 5 0 1
j,i,t,s 0 6 0 2
A
j,i,t,s 1 4 1 0
j,i,t,s 1 5 1 1
j,i,t,s 1 6 1 2
A
j,i,t,s 2 4 2 0
j,i,t,s 2 5 2 1
j,i,t,s 2 6 2 2
A
B
j,i,t,s 0 5 0 0
j,i,t,s 0 6 0 1
j,i,t,s 0 7 0 2
A
j,i,t,s 1 5 1 0
j,i,t,s 1 6 1 1
j,i,t,s 1 7 1 2
A
j,i,t,s 2 5 2 0
j,i,t,s 2 6 2 1
j,i,t,s 2 7 2 2
A
B
j,i,t,s 0 6 0 0
j,i,t,s 0 7 0 1
j,i,t,s 0 8 0 2
A
j,i,t,s 1 6 1 0
j,i,t,s 1 7 1 1
j,i,t,

j,i,t,s 2 14 0 1
j,i,t,s 2 15 0 2
A
j,i,t,s 3 13 1 0
j,i,t,s 3 14 1 1
j,i,t,s 3 15 1 2
A
j,i,t,s 4 13 2 0
j,i,t,s 4 14 2 1
j,i,t,s 4 15 2 2
A
B
j,i,t,s 2 14 0 0
j,i,t,s 2 15 0 1
j,i,t,s 2 16 0 2
A
j,i,t,s 3 14 1 0
j,i,t,s 3 15 1 1
j,i,t,s 3 16 1 2
A
j,i,t,s 4 14 2 0
j,i,t,s 4 15 2 1
j,i,t,s 4 16 2 2
A
B
j,i,t,s 2 15 0 0
j,i,t,s 2 16 0 1
j,i,t,s 2 17 0 2
A
j,i,t,s 3 15 1 0
j,i,t,s 3 16 1 1
j,i,t,s 3 17 1 2
A
j,i,t,s 4 15 2 0
j,i,t,s 4 16 2 1
j,i,t,s 4 17 2 2
A
B
j,i,t,s 2 16 0 0
j,i,t,s 2 17 0 1
j,i,t,s 2 18 0 2
A
j,i,t,s 3 16 1 0
j,i,t,s 3 17 1 1
j,i,t,s 3 18 1 2
A
j,i,t,s 4 16 2 0
j,i,t,s 4 17 2 1
j,i,t,s 4 18 2 2
A
B
j,i,t,s 2 17 0 0
j,i,t,s 2 18 0 1
j,i,t,s 2 19 0 2
A
j,i,t,s 3 17 1 0
j,i,t,s 3 18 1 1
j,i,t,s 3 19 1 2
A
j,i,t,s 4 17 2 0
j,i,t,s 4 18 2 1
j,i,t,s 4 19 2 2
A
B
j,i,t,s 2 18 0 0
j,i,t,s 2 19 0 1
j,i,t,s 2 20 0 2
A
j,i,t,s 3 18 1 0
j,i,t,s 3 19 1 1
j,i,t,s 3 20 1 2
A
j,i,t,s 4 18 2 0
j,i,t,s 4 19 2 1
j,i,t,s 4 20 2 2
A
B
j,i,t,s 2 19 0 0
j,i,t,s 2 20 0 1
j,i,t,s 2 21 0 2


j,i,t,s 8 18 2 0
j,i,t,s 8 19 2 1
j,i,t,s 8 20 2 2
A
B
j,i,t,s 6 19 0 0
j,i,t,s 6 20 0 1
j,i,t,s 6 21 0 2
A
j,i,t,s 7 19 1 0
j,i,t,s 7 20 1 1
j,i,t,s 7 21 1 2
A
j,i,t,s 8 19 2 0
j,i,t,s 8 20 2 1
j,i,t,s 8 21 2 2
A
B
j,i,t,s 6 20 0 0
j,i,t,s 6 21 0 1
j,i,t,s 6 22 0 2
A
j,i,t,s 7 20 1 0
j,i,t,s 7 21 1 1
j,i,t,s 7 22 1 2
A
j,i,t,s 8 20 2 0
j,i,t,s 8 21 2 1
j,i,t,s 8 22 2 2
A
B
j,i,t,s 6 21 0 0
j,i,t,s 6 22 0 1
j,i,t,s 6 23 0 2
A
j,i,t,s 7 21 1 0
j,i,t,s 7 22 1 1
j,i,t,s 7 23 1 2
A
j,i,t,s 8 21 2 0
j,i,t,s 8 22 2 1
j,i,t,s 8 23 2 2
A
B
j,i,t,s 6 22 0 0
j,i,t,s 6 23 0 1
j,i,t,s 6 24 0 2
A
j,i,t,s 7 22 1 0
j,i,t,s 7 23 1 1
j,i,t,s 7 24 1 2
A
j,i,t,s 8 22 2 0
j,i,t,s 8 23 2 1
j,i,t,s 8 24 2 2
A
B
j,i,t,s 6 23 0 0
j,i,t,s 6 24 0 1
j,i,t,s 6 25 0 2
A
j,i,t,s 7 23 1 0
j,i,t,s 7 24 1 1
j,i,t,s 7 25 1 2
A
j,i,t,s 8 23 2 0
j,i,t,s 8 24 2 1
j,i,t,s 8 25 2 2
A
B
j,i,t,s 6 24 0 0
j,i,t,s 6 25 0 1
j,i,t,s 6 26 0 2
A
j,i,t,s 7 24 1 0
j,i,t,s 7 25 1 1
j,i,t,s 7 26 1 2
A
j,i,t,s 8 24 2 0
j,i,t,s 8 25 2 1


j,i,t,s 11 2 2 1
j,i,t,s 11 3 2 2
A
B
j,i,t,s 9 2 0 0
j,i,t,s 9 3 0 1
j,i,t,s 9 4 0 2
A
j,i,t,s 10 2 1 0
j,i,t,s 10 3 1 1
j,i,t,s 10 4 1 2
A
j,i,t,s 11 2 2 0
j,i,t,s 11 3 2 1
j,i,t,s 11 4 2 2
A
B
j,i,t,s 9 3 0 0
j,i,t,s 9 4 0 1
j,i,t,s 9 5 0 2
A
j,i,t,s 10 3 1 0
j,i,t,s 10 4 1 1
j,i,t,s 10 5 1 2
A
j,i,t,s 11 3 2 0
j,i,t,s 11 4 2 1
j,i,t,s 11 5 2 2
A
B
j,i,t,s 9 4 0 0
j,i,t,s 9 5 0 1
j,i,t,s 9 6 0 2
A
j,i,t,s 10 4 1 0
j,i,t,s 10 5 1 1
j,i,t,s 10 6 1 2
A
j,i,t,s 11 4 2 0
j,i,t,s 11 5 2 1
j,i,t,s 11 6 2 2
A
B
j,i,t,s 9 5 0 0
j,i,t,s 9 6 0 1
j,i,t,s 9 7 0 2
A
j,i,t,s 10 5 1 0
j,i,t,s 10 6 1 1
j,i,t,s 10 7 1 2
A
j,i,t,s 11 5 2 0
j,i,t,s 11 6 2 1
j,i,t,s 11 7 2 2
A
B
j,i,t,s 9 6 0 0
j,i,t,s 9 7 0 1
j,i,t,s 9 8 0 2
A
j,i,t,s 10 6 1 0
j,i,t,s 10 7 1 1
j,i,t,s 10 8 1 2
A
j,i,t,s 11 6 2 0
j,i,t,s 11 7 2 1
j,i,t,s 11 8 2 2
A
B
j,i,t,s 9 7 0 0
j,i,t,s 9 8 0 1
j,i,t,s 9 9 0 2
A
j,i,t,s 10 7 1 0
j,i,t,s 10 8 1 1
j,i,t,s 10 9 1 2
A
j,i,t,s 11 7 2 0
j,i,t,s 11 8 2 1
j,i,t,s 11 9 2 2
A
B
j,i,t,s 9 8 0 

j,i,t,s 11 11 0 0
j,i,t,s 11 12 0 1
j,i,t,s 11 13 0 2
A
j,i,t,s 12 11 1 0
j,i,t,s 12 12 1 1
j,i,t,s 12 13 1 2
A
j,i,t,s 13 11 2 0
j,i,t,s 13 12 2 1
j,i,t,s 13 13 2 2
A
B
j,i,t,s 11 12 0 0
j,i,t,s 11 13 0 1
j,i,t,s 11 14 0 2
A
j,i,t,s 12 12 1 0
j,i,t,s 12 13 1 1
j,i,t,s 12 14 1 2
A
j,i,t,s 13 12 2 0
j,i,t,s 13 13 2 1
j,i,t,s 13 14 2 2
A
B
j,i,t,s 11 13 0 0
j,i,t,s 11 14 0 1
j,i,t,s 11 15 0 2
A
j,i,t,s 12 13 1 0
j,i,t,s 12 14 1 1
j,i,t,s 12 15 1 2
A
j,i,t,s 13 13 2 0
j,i,t,s 13 14 2 1
j,i,t,s 13 15 2 2
A
B
j,i,t,s 11 14 0 0
j,i,t,s 11 15 0 1
j,i,t,s 11 16 0 2
A
j,i,t,s 12 14 1 0
j,i,t,s 12 15 1 1
j,i,t,s 12 16 1 2
A
j,i,t,s 13 14 2 0
j,i,t,s 13 15 2 1
j,i,t,s 13 16 2 2
A
B
j,i,t,s 11 15 0 0
j,i,t,s 11 16 0 1
j,i,t,s 11 17 0 2
A
j,i,t,s 12 15 1 0
j,i,t,s 12 16 1 1
j,i,t,s 12 17 1 2
A
j,i,t,s 13 15 2 0
j,i,t,s 13 16 2 1
j,i,t,s 13 17 2 2
A
B
j,i,t,s 11 16 0 0
j,i,t,s 11 17 0 1
j,i,t,s 11 18 0 2
A
j,i,t,s 12 16 1 0
j,i,t,s 12 17 1 1
j,i,t,s 12 18 1 2
A
j,i,t,s 13 16 2 0
j,i,t,s 13 17 2 1
j,

j,i,t,s 15 16 1 2
A
j,i,t,s 16 14 2 0
j,i,t,s 16 15 2 1
j,i,t,s 16 16 2 2
A
B
j,i,t,s 14 15 0 0
j,i,t,s 14 16 0 1
j,i,t,s 14 17 0 2
A
j,i,t,s 15 15 1 0
j,i,t,s 15 16 1 1
j,i,t,s 15 17 1 2
A
j,i,t,s 16 15 2 0
j,i,t,s 16 16 2 1
j,i,t,s 16 17 2 2
A
B
j,i,t,s 14 16 0 0
j,i,t,s 14 17 0 1
j,i,t,s 14 18 0 2
A
j,i,t,s 15 16 1 0
j,i,t,s 15 17 1 1
j,i,t,s 15 18 1 2
A
j,i,t,s 16 16 2 0
j,i,t,s 16 17 2 1
j,i,t,s 16 18 2 2
A
B
j,i,t,s 14 17 0 0
j,i,t,s 14 18 0 1
j,i,t,s 14 19 0 2
A
j,i,t,s 15 17 1 0
j,i,t,s 15 18 1 1
j,i,t,s 15 19 1 2
A
j,i,t,s 16 17 2 0
j,i,t,s 16 18 2 1
j,i,t,s 16 19 2 2
A
B
j,i,t,s 14 18 0 0
j,i,t,s 14 19 0 1
j,i,t,s 14 20 0 2
A
j,i,t,s 15 18 1 0
j,i,t,s 15 19 1 1
j,i,t,s 15 20 1 2
A
j,i,t,s 16 18 2 0
j,i,t,s 16 19 2 1
j,i,t,s 16 20 2 2
A
B
j,i,t,s 14 19 0 0
j,i,t,s 14 20 0 1
j,i,t,s 14 21 0 2
A
j,i,t,s 15 19 1 0
j,i,t,s 15 20 1 1
j,i,t,s 15 21 1 2
A
j,i,t,s 16 19 2 0
j,i,t,s 16 20 2 1
j,i,t,s 16 21 2 2
A
B
j,i,t,s 14 20 0 0
j,i,t,s 14 21 0 1
j,i,t,s 14 22 0 2
A
j,i,t,s 15 20 1 

j,i,t,s 18 18 2 1
j,i,t,s 18 19 2 2
A
B
j,i,t,s 16 18 0 0
j,i,t,s 16 19 0 1
j,i,t,s 16 20 0 2
A
j,i,t,s 17 18 1 0
j,i,t,s 17 19 1 1
j,i,t,s 17 20 1 2
A
j,i,t,s 18 18 2 0
j,i,t,s 18 19 2 1
j,i,t,s 18 20 2 2
A
B
j,i,t,s 16 19 0 0
j,i,t,s 16 20 0 1
j,i,t,s 16 21 0 2
A
j,i,t,s 17 19 1 0
j,i,t,s 17 20 1 1
j,i,t,s 17 21 1 2
A
j,i,t,s 18 19 2 0
j,i,t,s 18 20 2 1
j,i,t,s 18 21 2 2
A
B
j,i,t,s 16 20 0 0
j,i,t,s 16 21 0 1
j,i,t,s 16 22 0 2
A
j,i,t,s 17 20 1 0
j,i,t,s 17 21 1 1
j,i,t,s 17 22 1 2
A
j,i,t,s 18 20 2 0
j,i,t,s 18 21 2 1
j,i,t,s 18 22 2 2
A
B
j,i,t,s 16 21 0 0
j,i,t,s 16 22 0 1
j,i,t,s 16 23 0 2
A
j,i,t,s 17 21 1 0
j,i,t,s 17 22 1 1
j,i,t,s 17 23 1 2
A
j,i,t,s 18 21 2 0
j,i,t,s 18 22 2 1
j,i,t,s 18 23 2 2
A
B
j,i,t,s 16 22 0 0
j,i,t,s 16 23 0 1
j,i,t,s 16 24 0 2
A
j,i,t,s 17 22 1 0
j,i,t,s 17 23 1 1
j,i,t,s 17 24 1 2
A
j,i,t,s 18 22 2 0
j,i,t,s 18 23 2 1
j,i,t,s 18 24 2 2
A
B
j,i,t,s 16 23 0 0
j,i,t,s 16 24 0 1
j,i,t,s 16 25 0 2
A
j,i,t,s 17 23 1 0
j,i,t,s 17 24 1 1
j,i,t,s 17 25 1 2


j,i,t,s 18 15 0 0
j,i,t,s 18 16 0 1
j,i,t,s 18 17 0 2
A
j,i,t,s 19 15 1 0
j,i,t,s 19 16 1 1
j,i,t,s 19 17 1 2
A
j,i,t,s 20 15 2 0
j,i,t,s 20 16 2 1
j,i,t,s 20 17 2 2
A
B
j,i,t,s 18 16 0 0
j,i,t,s 18 17 0 1
j,i,t,s 18 18 0 2
A
j,i,t,s 19 16 1 0
j,i,t,s 19 17 1 1
j,i,t,s 19 18 1 2
A
j,i,t,s 20 16 2 0
j,i,t,s 20 17 2 1
j,i,t,s 20 18 2 2
A
B
j,i,t,s 18 17 0 0
j,i,t,s 18 18 0 1
j,i,t,s 18 19 0 2
A
j,i,t,s 19 17 1 0
j,i,t,s 19 18 1 1
j,i,t,s 19 19 1 2
A
j,i,t,s 20 17 2 0
j,i,t,s 20 18 2 1
j,i,t,s 20 19 2 2
A
B
j,i,t,s 18 18 0 0
j,i,t,s 18 19 0 1
j,i,t,s 18 20 0 2
A
j,i,t,s 19 18 1 0
j,i,t,s 19 19 1 1
j,i,t,s 19 20 1 2
A
j,i,t,s 20 18 2 0
j,i,t,s 20 19 2 1
j,i,t,s 20 20 2 2
A
B
j,i,t,s 18 19 0 0
j,i,t,s 18 20 0 1
j,i,t,s 18 21 0 2
A
j,i,t,s 19 19 1 0
j,i,t,s 19 20 1 1
j,i,t,s 19 21 1 2
A
j,i,t,s 20 19 2 0
j,i,t,s 20 20 2 1
j,i,t,s 20 21 2 2
A
B
j,i,t,s 18 20 0 0
j,i,t,s 18 21 0 1
j,i,t,s 18 22 0 2
A
j,i,t,s 19 20 1 0
j,i,t,s 19 21 1 1
j,i,t,s 19 22 1 2
A
j,i,t,s 20 20 2 0
j,i,t,s 20 21 2 1
j,

j,i,t,s 23 6 2 1
j,i,t,s 23 7 2 2
A
B
j,i,t,s 21 6 0 0
j,i,t,s 21 7 0 1
j,i,t,s 21 8 0 2
A
j,i,t,s 22 6 1 0
j,i,t,s 22 7 1 1
j,i,t,s 22 8 1 2
A
j,i,t,s 23 6 2 0
j,i,t,s 23 7 2 1
j,i,t,s 23 8 2 2
A
B
j,i,t,s 21 7 0 0
j,i,t,s 21 8 0 1
j,i,t,s 21 9 0 2
A
j,i,t,s 22 7 1 0
j,i,t,s 22 8 1 1
j,i,t,s 22 9 1 2
A
j,i,t,s 23 7 2 0
j,i,t,s 23 8 2 1
j,i,t,s 23 9 2 2
A
B
j,i,t,s 21 8 0 0
j,i,t,s 21 9 0 1
j,i,t,s 21 10 0 2
A
j,i,t,s 22 8 1 0
j,i,t,s 22 9 1 1
j,i,t,s 22 10 1 2
A
j,i,t,s 23 8 2 0
j,i,t,s 23 9 2 1
j,i,t,s 23 10 2 2
A
B
j,i,t,s 21 9 0 0
j,i,t,s 21 10 0 1
j,i,t,s 21 11 0 2
A
j,i,t,s 22 9 1 0
j,i,t,s 22 10 1 1
j,i,t,s 22 11 1 2
A
j,i,t,s 23 9 2 0
j,i,t,s 23 10 2 1
j,i,t,s 23 11 2 2
A
B
j,i,t,s 21 10 0 0
j,i,t,s 21 11 0 1
j,i,t,s 21 12 0 2
A
j,i,t,s 22 10 1 0
j,i,t,s 22 11 1 1
j,i,t,s 22 12 1 2
A
j,i,t,s 23 10 2 0
j,i,t,s 23 11 2 1
j,i,t,s 23 12 2 2
A
B
j,i,t,s 21 11 0 0
j,i,t,s 21 12 0 1
j,i,t,s 21 13 0 2
A
j,i,t,s 22 11 1 0
j,i,t,s 22 12 1 1
j,i,t,s 22 13 1 2
A
j,i,t,s 23 11 2 0
j,i,t,s 2

j,i,t,s 25 9 1 0
j,i,t,s 25 10 1 1
j,i,t,s 25 11 1 2
A
j,i,t,s 26 9 2 0
j,i,t,s 26 10 2 1
j,i,t,s 26 11 2 2
A
B
j,i,t,s 24 10 0 0
j,i,t,s 24 11 0 1
j,i,t,s 24 12 0 2
A
j,i,t,s 25 10 1 0
j,i,t,s 25 11 1 1
j,i,t,s 25 12 1 2
A
j,i,t,s 26 10 2 0
j,i,t,s 26 11 2 1
j,i,t,s 26 12 2 2
A
B
j,i,t,s 24 11 0 0
j,i,t,s 24 12 0 1
j,i,t,s 24 13 0 2
A
j,i,t,s 25 11 1 0
j,i,t,s 25 12 1 1
j,i,t,s 25 13 1 2
A
j,i,t,s 26 11 2 0
j,i,t,s 26 12 2 1
j,i,t,s 26 13 2 2
A
B
j,i,t,s 24 12 0 0
j,i,t,s 24 13 0 1
j,i,t,s 24 14 0 2
A
j,i,t,s 25 12 1 0
j,i,t,s 25 13 1 1
j,i,t,s 25 14 1 2
A
j,i,t,s 26 12 2 0
j,i,t,s 26 13 2 1
j,i,t,s 26 14 2 2
A
B
j,i,t,s 24 13 0 0
j,i,t,s 24 14 0 1
j,i,t,s 24 15 0 2
A
j,i,t,s 25 13 1 0
j,i,t,s 25 14 1 1
j,i,t,s 25 15 1 2
A
j,i,t,s 26 13 2 0
j,i,t,s 26 14 2 1
j,i,t,s 26 15 2 2
A
B
j,i,t,s 24 14 0 0
j,i,t,s 24 15 0 1
j,i,t,s 24 16 0 2
A
j,i,t,s 25 14 1 0
j,i,t,s 25 15 1 1
j,i,t,s 25 16 1 2
A
j,i,t,s 26 14 2 0
j,i,t,s 26 15 2 1
j,i,t,s 26 16 2 2
A
B
j,i,t,s 24 15 0 0
j,i,t,s 24 16 0 1
j,

In [81]:
print(len(loss_out_arr_cul))

676


In [82]:
a_2d = np.reshape(loss_out_arr_cul,[26,26])

In [84]:
print(a_2d.shape)

(26, 26)


In [48]:
print(X_2d[0,0,0,0])

0


In [ ]:
print(a[0,0,0,0])

In [88]:
print(a_2d[0,0])

1.0


### フォワード　フィルタ数追加

In [313]:
# 手計算でフォワード　→フィルタ数複数想定

#a_1d=np.arange(N_h_out_int,N_h_out_int)
loss_out_arr_cul= []
#最終格納するリスト 追加
a_2d_ijm = np.empty((0,N_h_out_int), int)

#フィルタ分繰り返すを追加
for m in range (w_2d_re.shape[2]):
    loss_out_arr_cul= []
    for i in range(N_h_out_int):
        for  j in range(N_h_out_int):
            a = 0
            ab = 0
            for s in range(w_2d_re.shape[1]):
                for t in range(w_2d_re.shape[0]):
                    a += X_2d[0,0,i+s, j+t] * w_2d_re[s,t,m] 
            ab = a+b_2d
            loss_out_arr_cul.append(ab)
    a_2d_re = np.reshape(loss_out_arr_cul,[N_w_out_int,N_h_out_int]) #26,26
    a_2d_ijm = np.append(a_2d_ijm,np.array(a_2d_re), axis=0)
    print('loss_out_arr_cul',len(loss_out_arr_cul))
a_2d_ijm = np.reshape(a_2d_ijm,[w_2d_re.shape[2],N_w_out_int,N_h_out_int])
print('a_2d_ijm',a_2d_ijm.shape)

loss_out_arr_cul 676
loss_out_arr_cul 676
loss_out_arr_cul 676
a_2d_ijm (3, 26, 26)


In [161]:
test = np.empty((0,26), int)

test = np.append(test,np.array(a_2d_re), axis=0)



In [158]:
print(a_2d_re.shape)

(26, 26)


In [316]:
print(a_2d_ijm[0].shape)

(26, 26)


In [167]:
print(test.shape)

(78, 26)


In [166]:
test = np.append(test,np.array(a_2d_re), axis=0)

In [153]:
print(N_h_out_int)

26


In [171]:
test_re = np.reshape(test,[N_w_out_int,N_h_out_int,w_2d_re.shape[2]]) #26,26

In [267]:
print(test_re[0])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 「w」手計算でバックワード

In [105]:
# 手計算でバックワード
        
#重み（フィルタ）の結果格納のリスト
w_new_2d =[]
w_new = 0


for t in range(w_2d.shape[1]):
    for s in range(w_2d.shape[1]):
        w_new = 0
        for j in range(N_h_out_int):
            for i in range(N_h_out_int):
                w_new += a_2d[i,j] * X_2d[0,0,i+s, j+t]
                print('i,j,i+s,j+t',i,j,i+s,j+t)
        print('w_new',w_new)
        w_new_2d.append(ab)
w_2d_new = np.reshape(w_new_2d,[3,3])

i,j,i+s,j+t 0 0 0 0
i,j,i+s,j+t 1 0 1 0
i,j,i+s,j+t 2 0 2 0
i,j,i+s,j+t 3 0 3 0
i,j,i+s,j+t 4 0 4 0
i,j,i+s,j+t 5 0 5 0
i,j,i+s,j+t 6 0 6 0
i,j,i+s,j+t 7 0 7 0
i,j,i+s,j+t 8 0 8 0
i,j,i+s,j+t 9 0 9 0
i,j,i+s,j+t 10 0 10 0
i,j,i+s,j+t 11 0 11 0
i,j,i+s,j+t 12 0 12 0
i,j,i+s,j+t 13 0 13 0
i,j,i+s,j+t 14 0 14 0
i,j,i+s,j+t 15 0 15 0
i,j,i+s,j+t 16 0 16 0
i,j,i+s,j+t 17 0 17 0
i,j,i+s,j+t 18 0 18 0
i,j,i+s,j+t 19 0 19 0
i,j,i+s,j+t 20 0 20 0
i,j,i+s,j+t 21 0 21 0
i,j,i+s,j+t 22 0 22 0
i,j,i+s,j+t 23 0 23 0
i,j,i+s,j+t 24 0 24 0
i,j,i+s,j+t 25 0 25 0
i,j,i+s,j+t 0 1 0 1
i,j,i+s,j+t 1 1 1 1
i,j,i+s,j+t 2 1 2 1
i,j,i+s,j+t 3 1 3 1
i,j,i+s,j+t 4 1 4 1
i,j,i+s,j+t 5 1 5 1
i,j,i+s,j+t 6 1 6 1
i,j,i+s,j+t 7 1 7 1
i,j,i+s,j+t 8 1 8 1
i,j,i+s,j+t 9 1 9 1
i,j,i+s,j+t 10 1 10 1
i,j,i+s,j+t 11 1 11 1
i,j,i+s,j+t 12 1 12 1
i,j,i+s,j+t 13 1 13 1
i,j,i+s,j+t 14 1 14 1
i,j,i+s,j+t 15 1 15 1
i,j,i+s,j+t 16 1 16 1
i,j,i+s,j+t 17 1 17 1
i,j,i+s,j+t 18 1 18 1
i,j,i+s,j+t 19 1 19 1
i,j,i+s,j+t 20 1 20 1
i,j,i+

i,j,i+s,j+t 5 20 5 20
i,j,i+s,j+t 6 20 6 20
i,j,i+s,j+t 7 20 7 20
i,j,i+s,j+t 8 20 8 20
i,j,i+s,j+t 9 20 9 20
i,j,i+s,j+t 10 20 10 20
i,j,i+s,j+t 11 20 11 20
i,j,i+s,j+t 12 20 12 20
i,j,i+s,j+t 13 20 13 20
i,j,i+s,j+t 14 20 14 20
i,j,i+s,j+t 15 20 15 20
i,j,i+s,j+t 16 20 16 20
i,j,i+s,j+t 17 20 17 20
i,j,i+s,j+t 18 20 18 20
i,j,i+s,j+t 19 20 19 20
i,j,i+s,j+t 20 20 20 20
i,j,i+s,j+t 21 20 21 20
i,j,i+s,j+t 22 20 22 20
i,j,i+s,j+t 23 20 23 20
i,j,i+s,j+t 24 20 24 20
i,j,i+s,j+t 25 20 25 20
i,j,i+s,j+t 0 21 0 21
i,j,i+s,j+t 1 21 1 21
i,j,i+s,j+t 2 21 2 21
i,j,i+s,j+t 3 21 3 21
i,j,i+s,j+t 4 21 4 21
i,j,i+s,j+t 5 21 5 21
i,j,i+s,j+t 6 21 6 21
i,j,i+s,j+t 7 21 7 21
i,j,i+s,j+t 8 21 8 21
i,j,i+s,j+t 9 21 9 21
i,j,i+s,j+t 10 21 10 21
i,j,i+s,j+t 11 21 11 21
i,j,i+s,j+t 12 21 12 21
i,j,i+s,j+t 13 21 13 21
i,j,i+s,j+t 14 21 14 21
i,j,i+s,j+t 15 21 15 21
i,j,i+s,j+t 16 21 16 21
i,j,i+s,j+t 17 21 17 21
i,j,i+s,j+t 18 21 18 21
i,j,i+s,j+t 19 21 19 21
i,j,i+s,j+t 20 21 20 21
i,j,i+s,j+t 21 21 21 2

i,j,i+s,j+t 5 16 6 16
i,j,i+s,j+t 6 16 7 16
i,j,i+s,j+t 7 16 8 16
i,j,i+s,j+t 8 16 9 16
i,j,i+s,j+t 9 16 10 16
i,j,i+s,j+t 10 16 11 16
i,j,i+s,j+t 11 16 12 16
i,j,i+s,j+t 12 16 13 16
i,j,i+s,j+t 13 16 14 16
i,j,i+s,j+t 14 16 15 16
i,j,i+s,j+t 15 16 16 16
i,j,i+s,j+t 16 16 17 16
i,j,i+s,j+t 17 16 18 16
i,j,i+s,j+t 18 16 19 16
i,j,i+s,j+t 19 16 20 16
i,j,i+s,j+t 20 16 21 16
i,j,i+s,j+t 21 16 22 16
i,j,i+s,j+t 22 16 23 16
i,j,i+s,j+t 23 16 24 16
i,j,i+s,j+t 24 16 25 16
i,j,i+s,j+t 25 16 26 16
i,j,i+s,j+t 0 17 1 17
i,j,i+s,j+t 1 17 2 17
i,j,i+s,j+t 2 17 3 17
i,j,i+s,j+t 3 17 4 17
i,j,i+s,j+t 4 17 5 17
i,j,i+s,j+t 5 17 6 17
i,j,i+s,j+t 6 17 7 17
i,j,i+s,j+t 7 17 8 17
i,j,i+s,j+t 8 17 9 17
i,j,i+s,j+t 9 17 10 17
i,j,i+s,j+t 10 17 11 17
i,j,i+s,j+t 11 17 12 17
i,j,i+s,j+t 12 17 13 17
i,j,i+s,j+t 13 17 14 17
i,j,i+s,j+t 14 17 15 17
i,j,i+s,j+t 15 17 16 17
i,j,i+s,j+t 16 17 17 17
i,j,i+s,j+t 17 17 18 17
i,j,i+s,j+t 18 17 19 17
i,j,i+s,j+t 19 17 20 17
i,j,i+s,j+t 20 17 21 17
i,j,i+s,j+t 21 17 22

i,j,i+s,j+t 16 25 18 25
i,j,i+s,j+t 17 25 19 25
i,j,i+s,j+t 18 25 20 25
i,j,i+s,j+t 19 25 21 25
i,j,i+s,j+t 20 25 22 25
i,j,i+s,j+t 21 25 23 25
i,j,i+s,j+t 22 25 24 25
i,j,i+s,j+t 23 25 25 25
i,j,i+s,j+t 24 25 26 25
i,j,i+s,j+t 25 25 27 25
w_new 37014036.0
i,j,i+s,j+t 0 0 0 1
i,j,i+s,j+t 1 0 1 1
i,j,i+s,j+t 2 0 2 1
i,j,i+s,j+t 3 0 3 1
i,j,i+s,j+t 4 0 4 1
i,j,i+s,j+t 5 0 5 1
i,j,i+s,j+t 6 0 6 1
i,j,i+s,j+t 7 0 7 1
i,j,i+s,j+t 8 0 8 1
i,j,i+s,j+t 9 0 9 1
i,j,i+s,j+t 10 0 10 1
i,j,i+s,j+t 11 0 11 1
i,j,i+s,j+t 12 0 12 1
i,j,i+s,j+t 13 0 13 1
i,j,i+s,j+t 14 0 14 1
i,j,i+s,j+t 15 0 15 1
i,j,i+s,j+t 16 0 16 1
i,j,i+s,j+t 17 0 17 1
i,j,i+s,j+t 18 0 18 1
i,j,i+s,j+t 19 0 19 1
i,j,i+s,j+t 20 0 20 1
i,j,i+s,j+t 21 0 21 1
i,j,i+s,j+t 22 0 22 1
i,j,i+s,j+t 23 0 23 1
i,j,i+s,j+t 24 0 24 1
i,j,i+s,j+t 25 0 25 1
i,j,i+s,j+t 0 1 0 2
i,j,i+s,j+t 1 1 1 2
i,j,i+s,j+t 2 1 2 2
i,j,i+s,j+t 3 1 3 2
i,j,i+s,j+t 4 1 4 2
i,j,i+s,j+t 5 1 5 2
i,j,i+s,j+t 6 1 6 2
i,j,i+s,j+t 7 1 7 2
i,j,i+s,j+t 8 1 8 2
i,j,i+s,j+t

i,j,i+s,j+t 1 16 1 17
i,j,i+s,j+t 2 16 2 17
i,j,i+s,j+t 3 16 3 17
i,j,i+s,j+t 4 16 4 17
i,j,i+s,j+t 5 16 5 17
i,j,i+s,j+t 6 16 6 17
i,j,i+s,j+t 7 16 7 17
i,j,i+s,j+t 8 16 8 17
i,j,i+s,j+t 9 16 9 17
i,j,i+s,j+t 10 16 10 17
i,j,i+s,j+t 11 16 11 17
i,j,i+s,j+t 12 16 12 17
i,j,i+s,j+t 13 16 13 17
i,j,i+s,j+t 14 16 14 17
i,j,i+s,j+t 15 16 15 17
i,j,i+s,j+t 16 16 16 17
i,j,i+s,j+t 17 16 17 17
i,j,i+s,j+t 18 16 18 17
i,j,i+s,j+t 19 16 19 17
i,j,i+s,j+t 20 16 20 17
i,j,i+s,j+t 21 16 21 17
i,j,i+s,j+t 22 16 22 17
i,j,i+s,j+t 23 16 23 17
i,j,i+s,j+t 24 16 24 17
i,j,i+s,j+t 25 16 25 17
i,j,i+s,j+t 0 17 0 18
i,j,i+s,j+t 1 17 1 18
i,j,i+s,j+t 2 17 2 18
i,j,i+s,j+t 3 17 3 18
i,j,i+s,j+t 4 17 4 18
i,j,i+s,j+t 5 17 5 18
i,j,i+s,j+t 6 17 6 18
i,j,i+s,j+t 7 17 7 18
i,j,i+s,j+t 8 17 8 18
i,j,i+s,j+t 9 17 9 18
i,j,i+s,j+t 10 17 10 18
i,j,i+s,j+t 11 17 11 18
i,j,i+s,j+t 12 17 12 18
i,j,i+s,j+t 13 17 13 18
i,j,i+s,j+t 14 17 14 18
i,j,i+s,j+t 15 17 15 18
i,j,i+s,j+t 16 17 16 18
i,j,i+s,j+t 17 17 17 18
i,j,i+

i,j,i+s,j+t 3 9 4 10
i,j,i+s,j+t 4 9 5 10
i,j,i+s,j+t 5 9 6 10
i,j,i+s,j+t 6 9 7 10
i,j,i+s,j+t 7 9 8 10
i,j,i+s,j+t 8 9 9 10
i,j,i+s,j+t 9 9 10 10
i,j,i+s,j+t 10 9 11 10
i,j,i+s,j+t 11 9 12 10
i,j,i+s,j+t 12 9 13 10
i,j,i+s,j+t 13 9 14 10
i,j,i+s,j+t 14 9 15 10
i,j,i+s,j+t 15 9 16 10
i,j,i+s,j+t 16 9 17 10
i,j,i+s,j+t 17 9 18 10
i,j,i+s,j+t 18 9 19 10
i,j,i+s,j+t 19 9 20 10
i,j,i+s,j+t 20 9 21 10
i,j,i+s,j+t 21 9 22 10
i,j,i+s,j+t 22 9 23 10
i,j,i+s,j+t 23 9 24 10
i,j,i+s,j+t 24 9 25 10
i,j,i+s,j+t 25 9 26 10
i,j,i+s,j+t 0 10 1 11
i,j,i+s,j+t 1 10 2 11
i,j,i+s,j+t 2 10 3 11
i,j,i+s,j+t 3 10 4 11
i,j,i+s,j+t 4 10 5 11
i,j,i+s,j+t 5 10 6 11
i,j,i+s,j+t 6 10 7 11
i,j,i+s,j+t 7 10 8 11
i,j,i+s,j+t 8 10 9 11
i,j,i+s,j+t 9 10 10 11
i,j,i+s,j+t 10 10 11 11
i,j,i+s,j+t 11 10 12 11
i,j,i+s,j+t 12 10 13 11
i,j,i+s,j+t 13 10 14 11
i,j,i+s,j+t 14 10 15 11
i,j,i+s,j+t 15 10 16 11
i,j,i+s,j+t 16 10 17 11
i,j,i+s,j+t 17 10 18 11
i,j,i+s,j+t 18 10 19 11
i,j,i+s,j+t 19 10 20 11
i,j,i+s,j+t 20 10 21 11

i,j,i+s,j+t 0 24 1 25
i,j,i+s,j+t 1 24 2 25
i,j,i+s,j+t 2 24 3 25
i,j,i+s,j+t 3 24 4 25
i,j,i+s,j+t 4 24 5 25
i,j,i+s,j+t 5 24 6 25
i,j,i+s,j+t 6 24 7 25
i,j,i+s,j+t 7 24 8 25
i,j,i+s,j+t 8 24 9 25
i,j,i+s,j+t 9 24 10 25
i,j,i+s,j+t 10 24 11 25
i,j,i+s,j+t 11 24 12 25
i,j,i+s,j+t 12 24 13 25
i,j,i+s,j+t 13 24 14 25
i,j,i+s,j+t 14 24 15 25
i,j,i+s,j+t 15 24 16 25
i,j,i+s,j+t 16 24 17 25
i,j,i+s,j+t 17 24 18 25
i,j,i+s,j+t 18 24 19 25
i,j,i+s,j+t 19 24 20 25
i,j,i+s,j+t 20 24 21 25
i,j,i+s,j+t 21 24 22 25
i,j,i+s,j+t 22 24 23 25
i,j,i+s,j+t 23 24 24 25
i,j,i+s,j+t 24 24 25 25
i,j,i+s,j+t 25 24 26 25
i,j,i+s,j+t 0 25 1 26
i,j,i+s,j+t 1 25 2 26
i,j,i+s,j+t 2 25 3 26
i,j,i+s,j+t 3 25 4 26
i,j,i+s,j+t 4 25 5 26
i,j,i+s,j+t 5 25 6 26
i,j,i+s,j+t 6 25 7 26
i,j,i+s,j+t 7 25 8 26
i,j,i+s,j+t 8 25 9 26
i,j,i+s,j+t 9 25 10 26
i,j,i+s,j+t 10 25 11 26
i,j,i+s,j+t 11 25 12 26
i,j,i+s,j+t 12 25 13 26
i,j,i+s,j+t 13 25 14 26
i,j,i+s,j+t 14 25 15 26
i,j,i+s,j+t 15 25 16 26
i,j,i+s,j+t 16 25 17 26
i,j,i+

i,j,i+s,j+t 22 17 24 18
i,j,i+s,j+t 23 17 25 18
i,j,i+s,j+t 24 17 26 18
i,j,i+s,j+t 25 17 27 18
i,j,i+s,j+t 0 18 2 19
i,j,i+s,j+t 1 18 3 19
i,j,i+s,j+t 2 18 4 19
i,j,i+s,j+t 3 18 5 19
i,j,i+s,j+t 4 18 6 19
i,j,i+s,j+t 5 18 7 19
i,j,i+s,j+t 6 18 8 19
i,j,i+s,j+t 7 18 9 19
i,j,i+s,j+t 8 18 10 19
i,j,i+s,j+t 9 18 11 19
i,j,i+s,j+t 10 18 12 19
i,j,i+s,j+t 11 18 13 19
i,j,i+s,j+t 12 18 14 19
i,j,i+s,j+t 13 18 15 19
i,j,i+s,j+t 14 18 16 19
i,j,i+s,j+t 15 18 17 19
i,j,i+s,j+t 16 18 18 19
i,j,i+s,j+t 17 18 19 19
i,j,i+s,j+t 18 18 20 19
i,j,i+s,j+t 19 18 21 19
i,j,i+s,j+t 20 18 22 19
i,j,i+s,j+t 21 18 23 19
i,j,i+s,j+t 22 18 24 19
i,j,i+s,j+t 23 18 25 19
i,j,i+s,j+t 24 18 26 19
i,j,i+s,j+t 25 18 27 19
i,j,i+s,j+t 0 19 2 20
i,j,i+s,j+t 1 19 3 20
i,j,i+s,j+t 2 19 4 20
i,j,i+s,j+t 3 19 5 20
i,j,i+s,j+t 4 19 6 20
i,j,i+s,j+t 5 19 7 20
i,j,i+s,j+t 6 19 8 20
i,j,i+s,j+t 7 19 9 20
i,j,i+s,j+t 8 19 10 20
i,j,i+s,j+t 9 19 11 20
i,j,i+s,j+t 10 19 12 20
i,j,i+s,j+t 11 19 13 20
i,j,i+s,j+t 12 19 14 20
i,j,

i,j,i+s,j+t 11 10 11 12
i,j,i+s,j+t 12 10 12 12
i,j,i+s,j+t 13 10 13 12
i,j,i+s,j+t 14 10 14 12
i,j,i+s,j+t 15 10 15 12
i,j,i+s,j+t 16 10 16 12
i,j,i+s,j+t 17 10 17 12
i,j,i+s,j+t 18 10 18 12
i,j,i+s,j+t 19 10 19 12
i,j,i+s,j+t 20 10 20 12
i,j,i+s,j+t 21 10 21 12
i,j,i+s,j+t 22 10 22 12
i,j,i+s,j+t 23 10 23 12
i,j,i+s,j+t 24 10 24 12
i,j,i+s,j+t 25 10 25 12
i,j,i+s,j+t 0 11 0 13
i,j,i+s,j+t 1 11 1 13
i,j,i+s,j+t 2 11 2 13
i,j,i+s,j+t 3 11 3 13
i,j,i+s,j+t 4 11 4 13
i,j,i+s,j+t 5 11 5 13
i,j,i+s,j+t 6 11 6 13
i,j,i+s,j+t 7 11 7 13
i,j,i+s,j+t 8 11 8 13
i,j,i+s,j+t 9 11 9 13
i,j,i+s,j+t 10 11 10 13
i,j,i+s,j+t 11 11 11 13
i,j,i+s,j+t 12 11 12 13
i,j,i+s,j+t 13 11 13 13
i,j,i+s,j+t 14 11 14 13
i,j,i+s,j+t 15 11 15 13
i,j,i+s,j+t 16 11 16 13
i,j,i+s,j+t 17 11 17 13
i,j,i+s,j+t 18 11 18 13
i,j,i+s,j+t 19 11 19 13
i,j,i+s,j+t 20 11 20 13
i,j,i+s,j+t 21 11 21 13
i,j,i+s,j+t 22 11 22 13
i,j,i+s,j+t 23 11 23 13
i,j,i+s,j+t 24 11 24 13
i,j,i+s,j+t 25 11 25 13
i,j,i+s,j+t 0 12 0 14
i,j,i+s,j+t 1 

i,j,i+s,j+t 6 2 7 4
i,j,i+s,j+t 7 2 8 4
i,j,i+s,j+t 8 2 9 4
i,j,i+s,j+t 9 2 10 4
i,j,i+s,j+t 10 2 11 4
i,j,i+s,j+t 11 2 12 4
i,j,i+s,j+t 12 2 13 4
i,j,i+s,j+t 13 2 14 4
i,j,i+s,j+t 14 2 15 4
i,j,i+s,j+t 15 2 16 4
i,j,i+s,j+t 16 2 17 4
i,j,i+s,j+t 17 2 18 4
i,j,i+s,j+t 18 2 19 4
i,j,i+s,j+t 19 2 20 4
i,j,i+s,j+t 20 2 21 4
i,j,i+s,j+t 21 2 22 4
i,j,i+s,j+t 22 2 23 4
i,j,i+s,j+t 23 2 24 4
i,j,i+s,j+t 24 2 25 4
i,j,i+s,j+t 25 2 26 4
i,j,i+s,j+t 0 3 1 5
i,j,i+s,j+t 1 3 2 5
i,j,i+s,j+t 2 3 3 5
i,j,i+s,j+t 3 3 4 5
i,j,i+s,j+t 4 3 5 5
i,j,i+s,j+t 5 3 6 5
i,j,i+s,j+t 6 3 7 5
i,j,i+s,j+t 7 3 8 5
i,j,i+s,j+t 8 3 9 5
i,j,i+s,j+t 9 3 10 5
i,j,i+s,j+t 10 3 11 5
i,j,i+s,j+t 11 3 12 5
i,j,i+s,j+t 12 3 13 5
i,j,i+s,j+t 13 3 14 5
i,j,i+s,j+t 14 3 15 5
i,j,i+s,j+t 15 3 16 5
i,j,i+s,j+t 16 3 17 5
i,j,i+s,j+t 17 3 18 5
i,j,i+s,j+t 18 3 19 5
i,j,i+s,j+t 19 3 20 5
i,j,i+s,j+t 20 3 21 5
i,j,i+s,j+t 21 3 22 5
i,j,i+s,j+t 22 3 23 5
i,j,i+s,j+t 23 3 24 5
i,j,i+s,j+t 24 3 25 5
i,j,i+s,j+t 25 3 26 5
i,j,i+s,j+t 0 

i,j,i+s,j+t 23 19 24 21
i,j,i+s,j+t 24 19 25 21
i,j,i+s,j+t 25 19 26 21
i,j,i+s,j+t 0 20 1 22
i,j,i+s,j+t 1 20 2 22
i,j,i+s,j+t 2 20 3 22
i,j,i+s,j+t 3 20 4 22
i,j,i+s,j+t 4 20 5 22
i,j,i+s,j+t 5 20 6 22
i,j,i+s,j+t 6 20 7 22
i,j,i+s,j+t 7 20 8 22
i,j,i+s,j+t 8 20 9 22
i,j,i+s,j+t 9 20 10 22
i,j,i+s,j+t 10 20 11 22
i,j,i+s,j+t 11 20 12 22
i,j,i+s,j+t 12 20 13 22
i,j,i+s,j+t 13 20 14 22
i,j,i+s,j+t 14 20 15 22
i,j,i+s,j+t 15 20 16 22
i,j,i+s,j+t 16 20 17 22
i,j,i+s,j+t 17 20 18 22
i,j,i+s,j+t 18 20 19 22
i,j,i+s,j+t 19 20 20 22
i,j,i+s,j+t 20 20 21 22
i,j,i+s,j+t 21 20 22 22
i,j,i+s,j+t 22 20 23 22
i,j,i+s,j+t 23 20 24 22
i,j,i+s,j+t 24 20 25 22
i,j,i+s,j+t 25 20 26 22
i,j,i+s,j+t 0 21 1 23
i,j,i+s,j+t 1 21 2 23
i,j,i+s,j+t 2 21 3 23
i,j,i+s,j+t 3 21 4 23
i,j,i+s,j+t 4 21 5 23
i,j,i+s,j+t 5 21 6 23
i,j,i+s,j+t 6 21 7 23
i,j,i+s,j+t 7 21 8 23
i,j,i+s,j+t 8 21 9 23
i,j,i+s,j+t 9 21 10 23
i,j,i+s,j+t 10 21 11 23
i,j,i+s,j+t 11 21 12 23
i,j,i+s,j+t 12 21 13 23
i,j,i+s,j+t 13 21 14 23
i,j,i+

i,j,i+s,j+t 15 9 17 11
i,j,i+s,j+t 16 9 18 11
i,j,i+s,j+t 17 9 19 11
i,j,i+s,j+t 18 9 20 11
i,j,i+s,j+t 19 9 21 11
i,j,i+s,j+t 20 9 22 11
i,j,i+s,j+t 21 9 23 11
i,j,i+s,j+t 22 9 24 11
i,j,i+s,j+t 23 9 25 11
i,j,i+s,j+t 24 9 26 11
i,j,i+s,j+t 25 9 27 11
i,j,i+s,j+t 0 10 2 12
i,j,i+s,j+t 1 10 3 12
i,j,i+s,j+t 2 10 4 12
i,j,i+s,j+t 3 10 5 12
i,j,i+s,j+t 4 10 6 12
i,j,i+s,j+t 5 10 7 12
i,j,i+s,j+t 6 10 8 12
i,j,i+s,j+t 7 10 9 12
i,j,i+s,j+t 8 10 10 12
i,j,i+s,j+t 9 10 11 12
i,j,i+s,j+t 10 10 12 12
i,j,i+s,j+t 11 10 13 12
i,j,i+s,j+t 12 10 14 12
i,j,i+s,j+t 13 10 15 12
i,j,i+s,j+t 14 10 16 12
i,j,i+s,j+t 15 10 17 12
i,j,i+s,j+t 16 10 18 12
i,j,i+s,j+t 17 10 19 12
i,j,i+s,j+t 18 10 20 12
i,j,i+s,j+t 19 10 21 12
i,j,i+s,j+t 20 10 22 12
i,j,i+s,j+t 21 10 23 12
i,j,i+s,j+t 22 10 24 12
i,j,i+s,j+t 23 10 25 12
i,j,i+s,j+t 24 10 26 12
i,j,i+s,j+t 25 10 27 12
i,j,i+s,j+t 0 11 2 13
i,j,i+s,j+t 1 11 3 13
i,j,i+s,j+t 2 11 4 13
i,j,i+s,j+t 3 11 5 13
i,j,i+s,j+t 4 11 6 13
i,j,i+s,j+t 5 11 7 13
i,j,i+s,j

In [122]:
print(w_2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [106]:
print(w_2d_new)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### [w]バックフィルタ複数

In [183]:
# 手計算でバックワード
        
#重み（フィルタ）の結果格納のリスト
w_new_2d =[]
w_new = 0

#最終格納するリスト 追加
w_2d_ijm = np.empty((0,w_2d_re.shape[0]), int)



for m in range(a_2d_ijm.shape[2]):
    w_new_2d =[]
    for t in range(w_2d_re.shape[0]):
        for s in range(w_2d_re.shape[1]):
            w_new = 0
            for j in range(N_h_out_int):
                for i in range(N_h_out_int):
                    w_new += a_2d_ijm[i,j,m] * X_2d[0,0,i+s, j+t]
            w_new_2d.append(ab)
    w_2d_new = np.reshape(w_new_2d,[w_2d_re.shape[0],w_2d_re.shape[1]])
    w_2d_ijm = np.append(w_2d_ijm,np.array(w_2d_new), axis=0)
    print('w_new_2d',len(w_new_2d))
w_2d_ijm = np.reshape(w_2d_ijm,[w_2d_re.shape[0],w_2d_re.shape[1],w_2d_re.shape[2]])
print('w_2d_ijm',w_2d_ijm.shape)


w_new_2d 9
w_new_2d 9
w_new_2d 9
w_2d_ijm (3, 3, 3)


### 「X」バックワード手計算

In [146]:
# X バックワード手計算

#Xのアウトプットのリスト
x_new_2d =[]

for i in range(X_2d.shape[2]):
    delta_x = 0
    for j in range(X_2d.shape[3]):
        for s in range(w_2d.shape[0]):
            for t in range(w_2d.shape[1]):
                i_s=i-s
                j_t=j-t
            if i_s < 0:
                delta_x += 0*w_2d[s,t]
            else:
                if  i_s > N_h_out_int-1:
                    delta_x += 0*w_2d[s,t]
                else:
                    if j_t < 0:
                        delta_x += 0*w_2d[s,t]
                    else:
                        if  j_t > N_w_out_int-1: 
                            delta_x += 0*w_2d[s,t]
                        else:
                            delta_x += a_2d[i_s,j_t]*w_2d[s,t]
        x_new_2d.append(delta_x)

In [147]:
print(X_2d.shape[3])

28


In [119]:
print(len(x_new_2d))

784


In [120]:
28*28

784

In [186]:
print(len(x_new_2d))

784


### 「X」フィルタ複数バックワード手計算

In [189]:
# X バックワード手計算

#Xのアウトプットのリスト
x_new_2d =[]

#最終格納するリスト 追加
x_2d_ijm = np.empty((0,w_2d_re.shape[0]), int)




for m in range(a_2d_ijm.shape[2]):
    x_new_2d =[]
    for i in range(X_2d.shape[2]):
        delta_x = 0
        for j in range(X_2d.shape[3]):
            for s in range(w_2d.shape[0]):
                for t in range(w_2d.shape[1]):
                    i_s=i-s
                    j_t=j-t
                if i_s < 0:
                    delta_x += 0*w_2d_re[s,t,m]
                else:
                    if  i_s > N_h_out_int-1:
                        delta_x += 0*w_2d_re[s,t,m]
                    else:
                        if j_t < 0:
                            delta_x += 0*w_2d_re[s,t,m]
                        else:
                            if  j_t > N_w_out_int-1: 
                                delta_x += 0*w_2d_re[s,t,m]
                            else:
                                delta_x += a_2d_ijm[i_s,j_t,m]*w_2d_re[s,t,m]
            x_new_2d.append(delta_x)
            #print('x_new_2d',len(x_new_2d))
    x_2d_new += np.reshape(x_new_2d,[X_2d.shape[2],X_2d.shape[3]])
    print('x_2d_new',x_2d_new.shape)

x_2d_new (28, 28)
x_2d_new (28, 28)
x_2d_new (28, 28)


## 【問題2】2次元畳み込み後の出力サイズ

In [17]:
def output_size_2d(N,P,F,S):
    N_out = (N+2*P-F/S)+1
    return N_out

In [18]:
#フィルタを(3,3)にしたとき
N_h_out = output_size_2d(28,0,3,1)
N_w_out = output_size_2d(28,0,3,1)

In [20]:
print(N_h_out)
print(N_h_out_int)

26.0
26


In [19]:
N_h_out_int = np.array(N_h_out).astype(np.int)
N_w_out_int = np.array(N_w_out).astype(np.int)

## 【問題3】最大プーリング層の作成

In [191]:
print(a_2d_ijm.shape)

(26, 26, 3)


In [195]:
np.max(a_2d_ijm[0:2,0:2,0])

1.0

In [219]:
np.argmax(a_2d_ijm[0:2,0:2,1])

0

In [223]:
print(a_2d_ijm.shape)

(26, 26, 3)


In [225]:
print(a_2d_ijm[0:2,0:2])

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [203]:
aaaa = np.arange(4)
print(aaaa)
aaaa = np.reshape(aaaa,[2,2])
print(aaaa)

print(np.max(aaaa))
print(np.argmax(aaaa))

[0 1 2 3]
[[0 1]
 [2 3]]
3
3


In [205]:
NP_h_out = output_size_2d(26,0,2,2)
print(NP_h_out)

26.0


### プーリング手計算 フォワード

In [212]:
#ストライドのwサイズ
sw = 2
#ストライドのhサイズ
sh =2
#プーリング後のアウトプットサイズ
pw_out = 13
#プーリング後のアウトプットサイズ
ph_out = 13

In [307]:
#プーリングのアウトプットのリスト
p_new_2d =[]
#プーリングのマックス値のインデックスのリスト
p_ind_new_2d =[]


#最終格納するリスト 追加
p_2d_ijm = np.empty((0,pw_out), int)
p_ind_2d_ijm = np.empty((0,pw_out), int)



for m in range(a_2d_ijm.shape[2]):
    p_new_2d =[]
    p_ind_new_2d =[]
    for h in range(ph_out):
        for w in range(pw_out):
            p_max=np.max(a_2d_ijm[w*sw:w*sw+sw,h*sh:h*sh+sh,m])
            p_new_2d.append(p_max)
            p_max_ind=np.argmax(a_2d_ijm[w*sw:w*sw+sw,h*sh:h*sh+sh,m])
            p_ind_new_2d.append(p_max_ind)
    p_new_2d_re = np.reshape(p_new_2d,[pw_out,ph_out])
    p_ind_new_2d_re = np.reshape(p_ind_new_2d,[pw_out,ph_out])
    
    #リシェープしたものをm数アペンド
    p_2d_ijm = np.append(p_2d_ijm,np.array(p_new_2d_re), axis=0)
    p_ind_2d_ijm = np.append(p_ind_2d_ijm,np.array(p_ind_new_2d_re), axis=0)
    #print(p_2d_ijm)

#アペンドしたものを最終的にリシェーぷ
p_2d_ijm = np.reshape(p_2d_ijm,[a_2d_ijm.shape[2],pw_out,ph_out])
p_ind_2d_ijm = np.reshape(p_ind_2d_ijm,[a_2d_ijm.shape[2],pw_out,ph_out])

In [230]:
p_2d_ijm.shape

(13, 13, 3)

In [357]:
print(sw)

2


In [210]:
print(len(p_new_2d))

169


In [216]:
print(p_new_2d_re.shape)

(13, 13)


In [226]:
a_2d_ijm.shape[2]

3

In [269]:
#print(p_ind_2d_ijm)

In [291]:
#トランスポーず　試し
a = np.array([[1,1,1,1],[1,1,1,1]])
b = np.array([[2,2,2,2],[2,2,2,2]])
c = np.array([[3,3,3,3],[3,3,3,3]])

In [292]:
abc = np.empty((0,4), int)

In [286]:
print(a.shape)

(2, 4)


In [293]:
abc = np.append(abc,np.array(a), axis=0)
abc = np.append(abc,np.array(b), axis=0)
abc = np.append(abc,np.array(c), axis=0)

In [294]:
print(abc)

[[1 1 1 1]
 [1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [3 3 3 3]
 [3 3 3 3]]


In [296]:
np.reshape(abc,[3,2,4])

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [318]:
#プーリング　バックワード
# プーリング　p_2d_ijm
#プーリングのインデックス　p_ind_2d_ijm
print(a_2d_ijm[0,w*sw:w*sw+sw,h*sh:h*sh+sh])
print(p_ind_2d_ijm[0])

[[1. 1.]
 [1. 1.]]
[[0 0 0 3 1 0 0 0 1 0 0 0 3]
 [0 1 1 3 0 3 1 3 0 3 1 0 2]
 [3 1 0 1 0 2 3 2 0 3 0 1 0]
 [3 0 2 0 0 1 2 0 0 2 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 0 3 0 3 0 3 1 3 1 0 1]
 [3 0 1 1 0 2 1 2 0 3 3 3 0]
 [2 0 2 0 0 0 2 0 0 2 2 2 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 0 3 0 1 0 3 1 3 0 0 1]
 [3 1 3 1 3 1 1 3 0 3 1 3 0]
 [2 0 3 0 3 0 3 0 0 2 2 1 0]
 [2 0 2 0 2 0 2 0 0 0 0 0 0]]


In [354]:
print(p_2d_ijm[0])

[[1.000e+00 1.000e+00 1.000e+00 2.280e+02 3.900e+02 1.000e+00 1.000e+00
  1.000e+00 6.170e+02 1.000e+00 1.000e+00 1.000e+00 6.170e+02]
 [1.000e+00 1.803e+03 1.200e+01 2.042e+03 7.190e+02 2.035e+03 3.200e+02
  6.710e+02 1.859e+03 1.044e+03 1.445e+03 1.000e+00 1.451e+03]
 [2.810e+02 2.187e+03 1.336e+03 2.033e+03 1.000e+00 1.933e+03 1.587e+03
  1.903e+03 6.730e+02 1.797e+03 1.517e+03 1.679e+03 2.015e+03]
 [6.300e+02 9.080e+02 1.184e+03 9.730e+02 1.000e+00 1.131e+03 2.030e+02
  1.469e+03 1.000e+00 1.275e+03 1.000e+00 1.461e+03 7.900e+01]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
  1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [6.700e+01 1.267e+03 1.000e+00 2.003e+03 1.000e+00 7.410e+02 1.000e+00
  7.330e+02 1.360e+03 1.097e+03 2.510e+02 1.000e+00 1.492e+03]
 [8.140e+02 2.132e+03 1.432e+03 2.094e+03 1.000e+00 1.781e+03 1.142e+03
  1.838e+03 7.790e+02 2.152e+03 1.524e+03 1.566e+03 2.109e+03]
 [1.169e+03 1.283e+03 1.790e+03 1.372e+03 1.000e+00 1.7

In [337]:
asasa = a_2d_ijm[0,0:2,0:2]

In [353]:
asasa[0]

array([1., 1.])

### プーリングバックワード

In [379]:
#バックワード

#最終格納するリスト 追加

bk_p_2d = None
bk_p_2d = np.zeros(a_2d_ijm.shape)
print(a_2d_ijm.shape)

(3, 26, 26)


In [367]:
print(bk_p_2d.shape)

(3, 26, 26)


In [369]:
print(p_2d_ijm.shape)

(3, 13, 13)


In [382]:
for m in range(a_2d_ijm.shape[0]):
    for h in range(ph_out):
        for w in range(pw_out):
            #フォワードのとき利用した値をもう一度持ってきて同じように範囲指定
            x_pool=a_2d_ijm[m,w*sw:w*sw+sw,h*sh:h*sh+sh]
            #print(x_pool)
            mask = (x_pool == np.max(x_pool))
            #print(mask)
            bk_p_2d[m,w*sw:w*sw+sw,h*sh:h*sh+sh] = mask*p_2d_ijm[m,w,h]

In [372]:
print(bk_p_2d.shape)

(3, 26, 26)


## 【問題5】平滑化

In [242]:
p_2d_ijm.shape

(13, 13, 3)

In [344]:
#平にする数字を出す
print(p_2d_ijm.shape)
f_num = p_2d_ijm.shape[0]*p_2d_ijm.shape[1]*p_2d_ijm.shape[2]
print(f_num)

#平にリシェープ
f_p_2d_ijm = np.reshape(p_2d_ijm,[f_num,1])
print(f_p_2d_ijm.shape)

(3, 13, 13)
507
(507, 1)


In [349]:
#バック
print(np.reshape(f_p_2d_ijm,p_2d_ijm.shape)[0])

[[1.000e+00 1.000e+00 1.000e+00 2.280e+02 3.900e+02 1.000e+00 1.000e+00
  1.000e+00 6.170e+02 1.000e+00 1.000e+00 1.000e+00 6.170e+02]
 [1.000e+00 1.803e+03 1.200e+01 2.042e+03 7.190e+02 2.035e+03 3.200e+02
  6.710e+02 1.859e+03 1.044e+03 1.445e+03 1.000e+00 1.451e+03]
 [2.810e+02 2.187e+03 1.336e+03 2.033e+03 1.000e+00 1.933e+03 1.587e+03
  1.903e+03 6.730e+02 1.797e+03 1.517e+03 1.679e+03 2.015e+03]
 [6.300e+02 9.080e+02 1.184e+03 9.730e+02 1.000e+00 1.131e+03 2.030e+02
  1.469e+03 1.000e+00 1.275e+03 1.000e+00 1.461e+03 7.900e+01]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
  1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [6.700e+01 1.267e+03 1.000e+00 2.003e+03 1.000e+00 7.410e+02 1.000e+00
  7.330e+02 1.360e+03 1.097e+03 2.510e+02 1.000e+00 1.492e+03]
 [8.140e+02 2.132e+03 1.432e+03 2.094e+03 1.000e+00 1.781e+03 1.142e+03
  1.838e+03 7.790e+02 2.152e+03 1.524e+03 1.566e+03 2.109e+03]
 [1.169e+03 1.283e+03 1.790e+03 1.372e+03 1.000e+00 1.7

## 全部合わせてクラス化

### 初期の重み設定

#### 全結合

In [22]:
class SimpleInitializer:
    """
    ガウス分布によるシンプルな初期化
    Parameters
    ----------
    sigma : float
      ガウス分布の標準偏差
    """
    def __init__(self, sigma):
        self.sigma = sigma
        
    def W(self, n_nodes1, n_nodes2):
        """
        重みの初期化
        Parameters
        ----------
        n_nodes1 : int
          前の層のノード数
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        W :
        """
        W= self.sigma * np.random.randn(n_nodes1, n_nodes2)
        return W
    
    def B(self, n_nodes2):
        """
        バイアスの初期化
        Parameters
        ----------
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        B :
        """
        B =  np.random.randn(n_nodes2,)
        return B

#### コンボ

In [23]:
class SimpleInitializer_con:
    """
    ガウス分布によるシンプルな初期化
    Parameters
    ----------
    sigma : float
      ガウス分布の標準偏差
    """
    def __init__(self, sigma):
        self.sigma = sigma
        
    def W(self, fil_num, f_size):
        """
        重みの初期化
        Parameters
        ----------
        f_size : int
          フィルタのサイズ
        fil_num : int
          フィルタの数

        Returns
        ----------
        W :
        """
        W= self.sigma * np.random.randn(fil_num, f_size,f_size)
        return W
    
    def B(self, fil_num):
        """
        バイアスの初期化
        Parameters
        ----------
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        B :
        """
        B =  np.random.randn(fil_num,)
        return B

### コンボリューション

In [20]:
print(np.sum(a_2d_ijm,axis = 0).shape)

NameError: name 'a_2d_ijm' is not defined

In [106]:
class CONV:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self,N_in,Pading,fil_num,Slide,fil_size,initializer, optimizer):
        #self.optimizer = optimizer
        # 指定の重みとバイアスを代入
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.W=initializer.W(fil_num, fil_size)
        self.B =initializer.B(fil_num,)
        self.N_in = N_in
        self.Pading = Pading
        self.Fil = fil_size
        self.Slide = Slide
    
    def output_size(self,):
        N_ount = (self.N_in+2*self.Pading-self.Fil/self.Slide)+1
        return N_ount


    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        self.X = X
        print('ConvX',self.X.shape)
        
        #アウトプットサイズ
        self.N_h_out = self.output_size()
        self.N_h_out_int = np.array(self.N_h_out).astype(np.int)

        self.N_w_out = self.output_size()
        self.N_w_out_int = np.array(self.N_w_out).astype(np.int)

        
        #a_1d=np.arange(N_h_out_int,N_h_out_int)
        loss_out_arr_cul= []
        #最終格納するリスト 追加
        a_2d_ijm = np.empty((0,self.N_h_out_int), int)

        #フィルタ分繰り返すを追加
        for m in range (w_2d_re.shape[2]):
            loss_out_arr_cul= []
            for i in range(self.N_w_out_int ):
                for  j in range(self.N_h_out_int):
                    a = 0
                    ab = 0
                    for s in range(w_2d_re.shape[1]):
                        for t in range(w_2d_re.shape[0]):
                            a += self.X[0,i+s, j+t] * w_2d_re[m,s,t] 
                    ab = a+self.B[m]
                    loss_out_arr_cul.append(ab)
            a_2d_re = np.reshape(loss_out_arr_cul,[self.N_w_out_int ,self.N_h_out_int]) #26,26
            a_2d_ijm = np.append(a_2d_ijm,np.array(a_2d_re), axis=0)
            #print('loss_out_arr_cul',len(loss_out_arr_cul))
        a_2d_ijm = np.reshape(a_2d_ijm,[w_2d_re.shape[2],self.N_w_out_int ,self.N_h_out_int])
        #print('a_2d_ijm',a_2d_ijm.shape)

        return a_2d_ijm
      
    def backward(self, delta_a):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
 
        #バイアスをa_2d_ijmから算出
        self.B_new = np.sum(a_2d_ijm,axis = 0)
        
        #重み（フィルタ）の結果格納のリスト
        w_new_2d =[]
        w_new_pre = 0

        #最終格納するリスト 追加
        w_2d_ijm = np.empty((0,w_2d_re.shape[0]), int)


        for m in range(a_2d_ijm.shape[2]):
            w_new_2d =[]
            for t in range(w_2d_re.shape[0]):
                for s in range(w_2d_re.shape[1]):
                    w_new_pre = 0
                    for j in range(N_h_out_int):
                        for i in range(N_h_out_int):
                            w_new_pre += a_2d_ijm[i,j,m] * X_2d[0,0,i+s, j+t]
                    w_new_2d.append(w_new_pre)
            w_2d_new = np.reshape(w_new_2d,[w_2d_re.shape[0],w_2d_re.shape[1]])
            w_2d_ijm = np.append(w_2d_ijm,np.array(w_2d_new), axis=0)
            #print('w_new_2d',len(w_new_2d))
        self.W_new = np.reshape(w_2d_ijm,[w_2d_re.shape[0],w_2d_re.shape[1],w_2d_re.shape[2]])
        #print('w_2d_ijm',w_2d_ijm.shape)


            
        #Xの更新
        #Xのアウトプットのリスト
        x_new_2d =[]

        #最終格納するリスト 追加
        x_2d_ijm = np.empty((0,w_2d_re.shape[0]), int)


        for m in range(a_2d_ijm.shape[2]):
            x_new_2d =[]
            for i in range(X_2d.shape[2]):
                delta_x = 0
                for j in range(X_2d.shape[3]):
                    for s in range(w_2d.shape[0]):
                        for t in range(w_2d.shape[1]):
                            i_s=i-s
                            j_t=j-t
                        if i_s < 0:
                            delta_x += 0*w_2d_re[s,t,m]
                        else:
                            if  i_s > N_h_out_int-1:
                                delta_x += 0*w_2d_re[s,t,m]
                            else:
                                if j_t < 0:
                                    delta_x += 0*w_2d_re[s,t,m]
                                else:
                                    if  j_t > N_w_out_int-1: 
                                        delta_x += 0*w_2d_re[s,t,m]
                                    else:
                                        delta_x += a_2d_ijm[i_s,j_t,m]*w_2d_re[s,t,m]
                    x_new_2d.append(delta_x)
                    #print('x_new_2d',len(x_new_2d))
            x_2d_new += np.reshape(x_new_2d,[X_2d.shape[2],X_2d.shape[3]])
            #print('x_2d_new',x_2d_new.shape)
    
    
        # 更新
        self = self.optimizer.update(self)
        
        return x_2d_new

### 更新式

In [25]:
class SGD:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr):
        self.lr = lr
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """
        layer.W -= self.lr*layer.W_new
        layer.B -=  self.lr*layer.B_new

### マックスプーリグ

In [23]:
print(a_2d_ijm.shape)

NameError: name 'a_2d_ijm' is not defined

In [110]:
class MAX_pool:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    sw : int
      ストライドの幅
    pw_out : int
      プーリング後の出力
    """
    def __init__(self, sw,sh, pw_out):
        
        #ストライドのwサイズ
        self.sw = sw
        self.sh = sh
        #プーリング後のアウトプットサイズ
        self.pw_out = pw_out
        
    def forward(self, a_2d_ijm):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        #バックワード用に保存
        self.a_2d_ijm= a_2d_ijm
        
        #プーリングのアウトプットのリスト
        p_new_2d =[]
        #プーリングのマックス値のインデックスのリスト
        p_ind_new_2d =[]


        #最終格納するリスト 追加
        p_2d_ijm = np.empty((0,self.pw_out), int)
        p_ind_2d_ijm = np.empty((0,self.pw_out), int)
        
        print('max' ,a_2d_ijm.shape)
        print('a_2d_ijm.shape[2]',a_2d_ijm.shape[2])
        for m in range(a_2d_ijm.shape[0]):
            p_max = []
            p_new_2d =[]
            p_ind_new_2d =[]
            for h in range(self.pw_out):
                for w in range(self.pw_out):
                    #print('m',m)
                    p_max=np.max(a_2d_ijm[m,w*self.sw:w*self.sw+self.sw,h*self.sh:h*self.sh+self.sh])
                    #p_max=np.max(a_2d_ijm[w*self.sw:w*self.sw+self.sw,h*self.sw:h*self.sw+self.sw,m])
                    p_new_2d.append(p_max)
                    p_max_ind=np.argmax(a_2d_ijm[m,w*self.sw:w*self.sw+self.sw,h*self.sh:h*self.sh+self.sh])
                    #p_max_ind=np.argmax(a_2d_ijm[w*self.sw:w*self.sw+self.sw,h*self.sw:h*self.sw+self.sw,m])
                    p_ind_new_2d.append(p_max_ind)
            p_new_2d_re = np.reshape(p_new_2d,[self.pw_out,self.pw_out])
            p_ind_new_2d_re = np.reshape(p_ind_new_2d,[self.pw_out,self.pw_out])
    
            #リシェープしたものをm数アペンド
            p_2d_ijm = np.append(p_2d_ijm,np.array(p_new_2d_re), axis=0)
            p_ind_2d_ijm = np.append(p_ind_2d_ijm,np.array(p_ind_new_2d_re), axis=0)
            #print(p_2d_ijm)

        #アペンドしたものを最終的にリシェーぷ
        p_2d_ijm = np.reshape(p_2d_ijm,[a_2d_ijm.shape[0],self.pw_out,self.pw_out])
        p_ind_2d_ijm = np.reshape(p_ind_2d_ijm,[a_2d_ijm.shape[0],self.pw_out,self.pw_out])

        return p_2d_ijm
    
    def backward(self, p_2d_ijm):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """

        for m in range(self.a_2d_ijm.shape[0]):
            for h in range(self.pw_out):
                for w in range(self.pw_out):
                    #フォワードのとき利用した値をもう一度持ってきて同じように範囲指定
                    x_pool=self.a_2d_ijm[m,w*self.sw:w*self.sw+self.sw,h*self.sh:h*self.sh+self.sh]
                    #x_pool=self.a_2d_ijm[m,w*self.sw:w*self.sw+self.sw,h*self.sw:h*self.sw+self.sw]
                    #print(x_pool)
                    mask = (x_pool == np.max(x_pool))
                    #print(mask)
                    bk_p_2d[m,w*self.sw:w*self.sw+self.sw,h*self.sh:h*self.sh+self.sh] = mask*p_2d_ijm[m,w,h]
                    #bk_p_2d[m,w*self.sw:w*self.sw+self.sw,h*self.sw:h*self.sw+self.sw] = mask*p_2d_ijm[m,w,h]
        
        return bk_p_2d

### ふらっと

In [27]:
class FLAT:
    
    def forward(self, p_2d_ijm):
        #シェープ保持
        self.p_2d_ijm_shape = p_2d_ijm.shape
        #平にする数字を出す
        f_num = p_2d_ijm.shape[0]*p_2d_ijm.shape[1]*p_2d_ijm.shape[2]
        #print(f_num)

        #平にリシェープ
        f_p_2d_ijm = np.reshape(p_2d_ijm,[f_num,1])
        #print(f_p_2d_ijm.shape)
        return f_p_2d_ijm

    def backward(self, dp_2d_ijm):
        f_p_2d_ijm = np.reshape(p_2d_ijm,self.p_2d_ijm_shape)
        return f_p_2d_ijm

### 全結合

In [28]:
class FC:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self, n_nodes1, n_nodes2,initializer, optimizer):
        self.optimizer = optimizer
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.W=initializer.W(n_nodes1, n_nodes2)
        self.B =initializer.B(n_nodes2)
        
    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        self.X = X
        A = np.dot(X,self.W)+self.B
        
        return A
    
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        self.B_new = np.sum(dA,axis = 0)
        self.W_new = np.dot(self.X.T,dA)
        dZ = np.dot(dA,self.W.T)

        # 更新
        self = self.optimizer.update(self)
        
        return dZ

### 活性化関数

In [29]:
class Tanh():
    
    def __init__(self):
        #self.optimizer = optimizer
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        pass
    
    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        self.X = X
        self.A =np.tanh(X)
        
        return self.A
    
    def backward(self, dZ):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        dA = dZ*(1-np.tanh(self.A)**2)

        return dA

### ソフトマックス

In [30]:
class Softmax():
    
    def __init__(self):
        #self.optimizer = optimizer
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.loss_list = []
        pass
    
    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        Z : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """        
        #20サンプルのソフトマックス分子作成
        bunbo = np.sum(np.exp(X),axis=1)
        #20サンプル、10クラスと割り算できるようにリシェーぷ
        bunboT = np.reshape(bunbo,[X.shape[0],1])
        #ソフトマックス計算でZ3算出
        Z = np.exp(X)/bunboT
  
        return Z
    
    def backward(self, dZ,Y):
        #バックワード
        dA = dZ-Y
        #交差エントロピー
        loss = -np.sum(Y*np.log(dZ))/Y.shape[0]
        self.loss_list.append(loss)
        
        return dA,self.loss_list

### ミニバッチ

In [31]:
class GetMiniBatch:
    """
    ミニバッチを取得するイテレータ

    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
      訓練用データ
    y : 次の形のndarray, shape (n_samples, 1)
      正解値
    batch_size : int
      バッチサイズ
    seed : int
      NumPyの乱数のシード
    """
    def __init__(self, X, y, batch_size = 20, seed=0):
        self.batch_size = batch_size
        np.random.seed(seed)
        shuffle_index = np.random.permutation(np.arange(X.shape[0]))
        self._X = X[shuffle_index]
        self._y = y[shuffle_index]
        self._stop = np.ceil(X.shape[0]/self.batch_size).astype(np.int)

    def __len__(self):
        return self._stop

    def __getitem__(self,item):
        p0 = item*self.batch_size
        p1 = item*self.batch_size + self.batch_size
        return self._X[p0:p1], self._y[p0:p1]        

    def __iter__(self):
        self._counter = 0
        return self

    def __next__(self):
        if self._counter >= self._stop:
            raise StopIteration()
        p0 = self._counter*self.batch_size
        p1 = self._counter*self.batch_size + self.batch_size
        self._counter += 1
        return self._X[p0:p1], self._y[p0:p1]

### 合わせる

In [111]:
class Scratch2dCNNClassifier():
    
    def __init__(self, iter_num = 100,verbose = True,α=0.00001,n_features = 28,n_nodes1 = 128
                 ,sigma = 0.01,n_nodes2 = 64,n_output = 10,batchi_sumple=20,fil_num_1 = 32,fil_num_2=64,
                 fil_num_3=128,fil_size=3,fil_slide=1,max_fil_size=2,max_fil_slide= 2,Pading = 0,max_out_1=13,max_out_2=5,max_out_3=1):
        self.verbose = verbose
        self.lr = α
        self.n_features =n_features
        self.n_nodes1 = n_nodes1
        self.sigma = sigma
        self.n_nodes2=n_nodes2
        self.n_output=n_output
        self.batchi_sumple =batchi_sumple
        self.iter_num = iter_num
        self.fil_num_1 =fil_num_1
        self.fil_num_2 =fil_num_2
        self.fil_num_3 =fil_num_3
        self.fil_size=fil_size
        self.fil_slide=fil_slide
        self.max_fil_size=max_fil_size
        self.max_fil_slide=max_fil_slide
        self.Pading = Pading
        self.max_out_1=max_out_1
        self.max_out_2=max_out_2
        self.max_out_3=max_out_3
        
        pass
    
    
    def fit(self, X, y, X_val=None, y_val=None):
        #インスタンス化
        optimizer = SGD(self.lr)
              
        #CNNコンポ1
        self.CONV1 = CONV(self.n_features, self.Pading,self.fil_num_1, self.fil_slide,self.fil_size,SimpleInitializer_con(self.sigma), optimizer)
        self.MAX1 = MAX_pool(self.max_fil_size,self.max_fil_size,self.max_out_1)
       #CNNコンポ2
        self.CONV2 = CONV(self.n_features, self.Pading,self.fil_num_2, self.fil_slide,self.fil_size,SimpleInitializer_con(self.sigma), optimizer)
        self.MAX2 = MAX_pool(self.max_fil_size,self.max_fil_size,self.max_out_2)
       #CNNコンポ3
        self.CONV3 = CONV(self.n_features, self.Pading,self.fil_num_3, self.fil_slide,self.fil_size,SimpleInitializer_con(self.sigma), optimizer)
        self.MAX3 = MAX_pool(self.max_fil_size,self.max_fil_size,self.max_out_3)
        
        #フラット
        self.FLAT=FLAT()
        
        #全結合
        #self.FC1 = FC(self.n_features, self.n_nodes1, SimpleInitializer(self.n_nodes1), optimizer)
        #self.activation1 = Tanh()
        self.FC2 = FC(self.n_nodes1, self.n_nodes2, SimpleInitializer(self.sigma), optimizer)
        self.activation2 = Tanh()
        self.FC3 = FC(self.n_nodes2, self.n_output, SimpleInitializer(self.sigma), optimizer)
        self.activation3 = Softmax()
        
        #データを取得
        get_mini_batch = GetMiniBatch(X, y, batch_size=self.batchi_sumple)
        #ロスのリスト作成
        loss_list = []
        
        for i in range(self.iter_num):
            for mini_X_train, mini_y_train in get_mini_batch:
                #フォワード
                #A1 = self.FC1.forward(mini_X_train)
                #Z1 = self.activation1.forward(A1)
                
                C1 = self.CONV1.forward(mini_X_train)
                M1 = self.MAX1.forward(C1)
                C2 = self.CONV2.forward(M1)
                M2 = self.MAX2.forward(C2)
                C3 = self.CONV3.forward(M2)
                M3 = self.MAX3.forward(C3)
                
                #フラット
                F1 = self.FLAT.forward(M3)
                
                A2 = self.FC2.forward(F1)
                Z2 = self.activation2.forward(A2)
                A3 = self.FC3.forward(Z2)
                Z3 = self.activation3.forward(A3)
                
                #バックワード
                dA3,loss_list = self.activation3.backward(Z3, mini_y_train) # 交差エントロピー誤差とソフトマックスを合わせている
                dZ2 = self.FC3.backward(dA3)
                dA2 = self.activation2.backward(dZ2)
                dZ1 = self.FC2.backward(dA2)
                #dA1 = self.activation1.backward(dZ1)
                #dZ0 = self.FC1.backward(dA1) 
                
                dF1 = self.FLAT.backward(dZ1)
                
                dM3 = self.CONV3.backward(dF1)
                dC3 = self.CONV3.forward(dM3)
                dM2 = self.CONV2.forward(dC3)
                dC2 = self.CONV2.forward(dM2)
                dM1 = self.CONV1.forward(dC2)
                dC1 = self.CONV1.forward(dM1)                
                             
        return loss_list
    
    def predict(self, X):
         #フォワード
        A1 = self.FC1.forward(X)
        Z1 = self.activation1.forward(A1)
        A2 = self.FC2.forward(Z1)
        Z2 = self.activation2.forward(A2)
        A3 = self.FC3.forward(Z2)
        Z3 = self.activation3.forward(A3)

        pred = np.argmax(Z3,axis = 1)

        return pred

In [112]:
#インスタンス化
CNN2d =Scratch2dCNNClassifier()

In [113]:
loss_list = CNN2d.fit(X_train, y_train)

ConvX (20, 28, 28)
max (3, 26, 26)
a_2d_ijm.shape[2] 26
ConvX (3, 13, 13)


IndexError: index 13 is out of bounds for axis 2 with size 13

In [35]:
get_mini_batch = GetMiniBatch(X_train, y_train, batch_size=3)

In [36]:
print(get_mini_batch[0])

(array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8), array([3, 6, 6], dtype=uint8))


In [460]:
mini_x=get_mini_batch[0][0]

In [461]:
print(mini_x.shape)

(3, 28, 28)


## 【問題9】出力サイズとパラメータ数の計算