# Week4授業前課題3 オブジェクト指向の活用

## 【問題1】これまで利用してきたクラスの列挙

#### pandas.DataFrame  
class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)[source]  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

#### matplotlibにおいて、グラフを作成するための主なクラスは、figureとaxesである  
figureオブジェクトは、グラフを表示するためのウィンドウに相当する。
axesオブジェクトはグラフそのものである。  
https://helve-python.hatenablog.jp/entry/2017/11/05/000000

#### scikit-learn  
StandardScaler(標準化),LinearRegression(回帰)

ついでに  
https://deepage.net/features/pandas-numpy.html

疑問  
：クラスをインスタンス化して利用する場合とそのまま利用(Dataframe)するものの違いは？？
：matplotlibは命名規則に準じていない気持ち  

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

メソッド  
.head,.mean,.describe,.sum,info,.fit

インスタンス変数  
columns,  
**わからなかったので回答から**
DataFrame.head.loc,matplotlib.lines.Line2D. _linestyle, matplotlib.lines.Line2D._marker,KNeighborsClassifier.weights, KNeighborsClassifier.classes_,StandardScaler.mean_, StandardScaler.var_


インスタンス変数とは？？  
オブジェクトの中で値を保存しておくための利用されるのがインスタンス変数です。

ローカル変数をメソッド内で使用することも可能です。ただしローカル変数は一度メソッドを抜けてしまえば値は消えてしまいます。

インスタンス変数はクラス内で全メソッドで共通して使用することが出来ます。最初にどこかのメソッドで使用された時点でインスタンス変数は作成され、一度作成されたインスタンス変数は他のメソッドで値を取り出したり格納したりすることが出来るようになります。

---------
インスタンス変数とは、それぞれのインスタンスごとに独立した変数です。たとえば、クラスはいくつもインスタンスを生成することができますが、それぞれのインスタンス変数は別のものとして扱われ変数に値を代入しても、インスタンスごとに別々の値が保存されています。


参考：https://www.javadrive.jp/ruby/class/index4.html  
https://uxmilk.jp/41600

In [15]:
import pandas as pd
df = pd.DataFrame([0, 1, 2])
print(type(df.info()))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
0    3 non-null int64
dtypes: int64(1)
memory usage: 104.0 bytes
<class 'NoneType'>


## 【問題3】標準化クラスをスクラッチで作成

In [18]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [19]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


### ソースから

    def __init__(self, copy=True, with_mean=True, with_std=True):
        self.with_mean = with_mean
        self.with_std = with_std
        self.copy = copy

    def fit(self, X, y=None):
        """Compute the mean and std to be used for later scaling.
        Parameters
        ----------
        X : {array-like, sparse matrix}, shape [n_samples, n_features]
            The data used to compute the mean and standard deviation
            used for later scaling along the features axis.
        y
            Ignored
        """

        # Reset internal state before fitting
        self._reset()
        return self.partial_fit(X, y)

    def transform(self, X, y='deprecated', copy=None):
        """Perform standardization by centering and scaling
        Parameters
        ----------
        X : array-like, shape [n_samples, n_features]
            The data used to scale along the features axis.
        y : (ignored)
            .. deprecated:: 0.19
               This parameter will be removed in 0.21.
        copy : bool, optional (default: None)
            Copy the input X or not.
        """
        if not isinstance(y, string_types) or y != 'deprecated':
            warnings.warn("The parameter y on transform() is "
                          "deprecated since 0.19 and will be removed in 0.21",
                          DeprecationWarning)

        check_is_fitted(self, 'scale_')

        copy = copy if copy is not None else self.copy
        X = check_array(X, accept_sparse='csr', copy=copy, warn_on_dtype=True,
                        estimator=self, dtype=FLOAT_DTYPES,
                        force_all_finite='allow-nan')

        if sparse.issparse(X):
            if self.with_mean:
                raise ValueError(
                    "Cannot center sparse matrices: pass `with_mean=False` "
                    "instead. See docstring for motivation and alternatives.")
            if self.scale_ is not None:
                inplace_column_scale(X, 1 / self.scale_)
        else:
            if self.with_mean:
                X -= self.mean_
            if self.with_std:
                X /= self.scale_
        return X

## 【問題4】 四則演算を行うクラスの作成

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [20]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if type(value) not in (float, int):
            print("数字ではありません")
            return None
        else:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
            
            
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
    def mul(self, value2):
        """
        受け取った引数をself.valueでかける
        """
        self.value *= value2

    def div(self, value2):
        """
        受け取った引数をself.valueでわる
        """
        self.value /= value2

In [21]:
a = 1
b = 1.1
c = 'aaa'

In [10]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [22]:
example = ExampleClass(5)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5


In [20]:
example.add(3)
print("value : {}".format(example.value))

value : 6


In [19]:
example.sub(2)
print("value : {}".format(example.value))

value : 3


In [24]:
example.mul(2)
print("value : {}".format(example.value))

value : 10


In [23]:
example = ExampleClass('aaa')
print("value : {}".format(example.value))

数字ではありません


AttributeError: 'ExampleClass' object has no attribute 'value'