## Week2授業前課題3 行列積のスクラッチ

## 【問題1】行列積を手計算する

<計算方法>  
①Aの配列の1行目＆1列目(0.0)とBの配列の1列目＆1列目(0.0)を掛け合わせる
②Aの配列は「行方向」、Bは「列方向」に1づつ進み掛け合わせる  
   A(0,1)×B(1,0)  
③それぞれの方向に行と列が終わるまで繰り返し、終わったら合算する  
④③が終わったら次の行にうつり行が繰り返す。  


<問題の計算過程>  
(-1×0)+(2×0)+(3×2) (-1×-1)+(2×2)+(3×9) (-1×-1)+(2×-8)+(3×-1)  
(4×0)+(-5×0)+(6×2) (4×2)+(-5×2)+(6×9) (4×1)+(-5×-8)+(6×-1)  
(7×0)+(8×0)+(2×-9) (7×2)+(8×2)+(-9×9) (7×1)+(8×-8)+(-9×-1)  
  

<回答>  
  6 29 -20  
  12 52 38    
  -18 -51 -48  


## 【問題2】NumPyの関数による計算

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [5]:
print(np.dot(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [7]:
print(np.matmul(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [8]:
print(a_ndarray@b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装

In [116]:
print(a_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]


In [117]:
print(b_ndarray)

[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [101]:
print(a_ndarray[0,0])

-1


**回答**

In [114]:
k = 0
s = 3
c = 0
c_list=[]

    
for _ in range(s):
    c += a_ndarray[0,k]*b_ndarray[k,0]
    k +=1
c_list.append(c)
ab_ndarray = np.array(c_list)
print(c)
print(c_list)
print(ab_ndarray)

6
[6]
[6]


## 【問題4】行列積を行う関数の作成

In [25]:
def compute_gyo_seki (x,y):
    k = 0
    s = 3
    c = 0
    j =0
    i = 0
    
    c_list=np.zeros((x.shape[0], y.shape[1]))
    
    for i in range (x.shape[0]):
        for j in range (y.shape[1]):
            for k in range (x.shape[0]):
                c_list[i,j] += x[i, k]*y[k, j]
                
    return(c_list)

In [26]:
x = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
y= np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
compute_gyo_seki (x,y)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [47]:
#参考
list_arr1 = [[1, 2], [3, 4]]
list_arr2 = [[1, 2], [3, 4]]
 
result = []
for k, v in list_arr1:
    tmp = []
    for kk, vv in zip(*list_arr2):
        tmp.append(k * kk + v * vv)
    result.append(tmp)
print(result)

[[7, 10], [15, 22]]


## 【問題5】計算が定義されない入力を判定する

In [30]:
def compute_gyo_seki_err (x,y):
    k = 0
    s = 3
    c = 0
    j =0
    i = 0
    
    c_list=np.zeros((x.shape[0], y.shape[1]))
    
    if x.shape[1] == y.shape[0]:
        for i in range (x.shape[0]):
            for j in range (y.shape[1]):
                for k in range (x.shape[0]):
                    c_list[i,j] += x[i, k]*y[k, j]
        return(c_list)
    else:
        print("配列の数が合いません")
        return None

In [31]:
x_2 = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
y_2= np.array([[0, 2, 1], [0, 2, -8]])
compute_gyo_seki_err(x_2,y_2)

配列の数が合いません


## 【問題6】転置

In [32]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(d_ndarray)
print(e_ndarray)

[[-1  2  3]
 [ 4 -5  6]]
[[-9  8  7]
 [ 6 -5  4]]


In [36]:
# エラーになる
print(d_ndarray@e_ndarray)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [10]:
e_ndarray.transpose()

array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [11]:
e_ndarray.T

array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [37]:
# ひっくり返して
e_ndarray_t = e_ndarray.T
print(e_ndarray)

[[-9  8  7]
 [ 6 -5  4]]


In [39]:
#計算
print(np.dot(d_ndarray,e_ndarray_t))

[[ 46  -4]
 [-34  73]]
